<!DOCTYPE html><html lang="en-gb" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Erik Kusch">

  
  
  
    
  
  <meta name="description" content="Answers and solutions to the exercises belonging to chapter 4 in [Satistical Rethinking 2](https://xcelab.net/rm/statistical-rethinking/) by Richard McElreath.">

  
  <link rel="alternate" hreflang="en-gb" href="https://www.erikkusch.com/courses/rethinking/chapter-04/">

  


  
  
  
  <meta name="theme-color" content="#858383">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cutive+Mono%7CLora:400,700%7CRoboto:400,700&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-186216138-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-186216138-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://www.erikkusch.com/courses/rethinking/chapter-04/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@ErikKusch">
  <meta property="twitter:creator" content="@ErikKusch">
  
  <meta property="og:site_name" content="Erik Kusch">
  <meta property="og:url" content="https://www.erikkusch.com/courses/rethinking/chapter-04/">
  <meta property="og:title" content="Chapter 04 | Erik Kusch">
  <meta property="og:description" content="Answers and solutions to the exercises belonging to chapter 4 in [Satistical Rethinking 2](https://xcelab.net/rm/statistical-rethinking/) by Richard McElreath."><meta property="og:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg">
  <meta property="twitter:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg"><meta property="og:locale" content="en-gb">
  
    
      <meta property="article:published_time" content="2021-01-08T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2021-01-08T09:00:00&#43;01:00">
  

  



  


  


  





  <title>Chapter 04 | Erik Kusch</title>

</head>
<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  








  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-center" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/"><span>Home</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Courses & Workshops</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/courses/krigr/"><span>KrigR - State-of-the-Art Climate Data within R</span></a>
            
              <a class="dropdown-item" href="/courses/gbif/"><span>Accessing and Referencing GBIF Data for Research</span></a>
            
              <a class="dropdown-item" href="/courses/rethinking/"><span>Statistical Rethinking - Introduction to Bayesian Statistics</span></a>
            
              <a class="dropdown-item" href="/courses/bayes-nets/"><span>Bayesian Networks - Causality through Bayesian Approaches</span></a>
            
              <a class="dropdown-item" href="/courses/biostat101/"><span>Biostats 101 - An Introduction to Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/excursions-into-biostatistics/"><span>Biostats 301 - Excursions into Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/bftp-biome-detection/"><span>BFTP - First Steps in Macroecology in R</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/about"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://htmlpreview.github.io/?https://github.com/ErikKusch/Homepage/blob/master/static/media/CV_ErikKusch.html" target="_blank" rel="noopener"><span>CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  

<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
  <input name="q" type="search" class="form-control" placeholder="Search..." autocomplete="off">
  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/rethinking/">Overview</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/rethinking/chapter-02/">Seminars</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/courses/rethinking/chapter-02/">Chapter 01 &amp; 02</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-03/">Chapter 03</a>
      </li>
      
      <li class="active">
        <a href="/courses/rethinking/chapter-04/">Chapter 04</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-04b/">Chapter 04 (Extra Material)</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-05/">Chapter 05</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-06/">Chapter 06</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-07/">Chapter 07</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-08/">Chapter 08</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-09/">Chapter 09</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-11/">Chapter 10 &amp; 11</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-12/">Chapter 12</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-13/">Chapter 13</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-14/">Chapter 14</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-15/">Chapter 15</a>
      </li>
      
      <li >
        <a href="/courses/rethinking/chapter-16/">Chapter 16</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

    </div>

    
    <div class="d-none d-xl-block col-xl-2 docs-toc">
      <ul class="nav toc-top">
        <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
      </ul>

      <nav id="TableOfContents">
  <ul>
    <li><a href="#material">Material</a></li>
    <li><a href="#introduction">Introduction</a></li>
    <li><a href="#easy-exercises">Easy Exercises</a>
      <ul>
        <li><a href="#practice-e1">Practice E1</a></li>
        <li><a href="#practice-e2">Practice E2</a></li>
        <li><a href="#practice-e3">Practice E3</a></li>
        <li><a href="#practice-e4">Practice E4</a></li>
        <li><a href="#practice-e5">Practice E5</a></li>
      </ul>
    </li>
    <li><a href="#medium-exercises">Medium Exercises</a>
      <ul>
        <li><a href="#practice-m1">Practice M1</a></li>
        <li><a href="#practice-m2">Practice M2</a></li>
        <li><a href="#practice-m3">Practice M3</a></li>
        <li><a href="#practice-m4">Practice M4</a></li>
        <li><a href="#practice-m5">Practice M5</a></li>
        <li><a href="#practice-m6">Practice M6</a></li>
      </ul>
    </li>
    <li><a href="#hard-exercises">Hard Exercises</a>
      <ul>
        <li><a href="#practice-h1">Practice H1</a></li>
        <li><a href="#practice-h2">Practice H2</a></li>
        <li><a href="#practice-h3">Practice H3</a></li>
        <li><a href="#practice-h4">Practice H4</a></li>
      </ul>
    </li>
    <li><a href="#session-info">Session Info</a></li>
  </ul>
</nav>

      
    </div>
    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

      <article class="article">

        <div class="docs-article-container">
          <h1>Chapter 04</h1>

          <div class="article-style">
            <h1 id="geocentric-models">Geocentric Models</h1>
<h2 id="material">Material</h2>
<ul>
<li>
<a href="https://htmlpreview.github.io/?https://github.com/ErikKusch/Homepage/blob/master/static/courses/rethinking/3__08-01-2021_SUMMARY_-Linear-Regressions.html" target="_blank" rel="noopener">Slides Chapter 4</a></li>
</ul>
<h2 id="introduction">Introduction</h2>
<p>These are answers and solutions to the exercises at the end of chapter 4 in 
<a href="https://xcelab.net/rm/statistical-rethinking/" target="_blank" rel="noopener">Satistical Rethinking 2</a> by Richard McElreath. I have created these notes as a part of my ongoing involvement in the 
<a href="/project/aubayes/">AU Bayes Study Group</a>. Much of my inspiration for these solutions, where necessary, has been obtained from 
<a href="https://jmgirard.com/statistical-rethinking-ch4/" target="_blank" rel="noopener">Jeffrey Girard</a>.</p>
<h2 id="easy-exercises">Easy Exercises</h2>
<h3 id="practice-e1">Practice E1</h3>
<p><strong>Question:</strong> In the model definition below, which line is the likelihood?</p>
<ol>
<li>$y_i \sim Normal(\mu, \sigma)$</li>
<li>$\mu \sim Normal(0, 10)$</li>
<li>$\sigma \sim Uniform(0, 10)$</li>
</ol>
<p><strong>Answer:</strong> 1, $y_i \sim Normal(\mu, \sigma)$ - This is the likelihood specification (see also page 84 in the book). Everything else is a specification of priors.</p>
<h3 id="practice-e2">Practice E2</h3>
<p><strong>Question:</strong> In the model definition just above, how many parameters are in the posterior distribution?</p>
<p><strong>Answer:</strong> $y_i$ is not to be estimated, but represents the data we have at hand and want to understand through parameters. Both $\mu$ and $\sigma$ are parameters which we attempt to estimate.</p>
<h3 id="practice-e3">Practice E3</h3>
<p><strong>Question:</strong> Using the model definition above, write down the appropriate form of Bayes’ theorem that includes the proper likelihood and priors.</p>
<p><strong>Answer:</strong> Following the specification in the &ldquo;Overthinking&rdquo; box on page 87, we can write the Bayes' Theorem for the model above as:</p>
<p>$Pr(\mu, \sigma | y) = \frac{\prod_i Normal(y_i| \mu, \sigma) Normal(\mu| 0, 10) Uniform(\sigma | 0, 10)}{\int\int\prod_i Normal(y_i| \mu, \sigma) Normal(\mu| 0, 10) Uniform(\sigma | 0, 10) d\mu d\sigma}$</p>
<h3 id="practice-e4">Practice E4</h3>
<p><strong>Question:</strong> In the model definition below, which line is the linear model?</p>
<ol>
<li>$y_i \sim Normal(\mu, \sigma)$</li>
<li>$\mu_i=\alpha+\beta x_i$</li>
<li>$\alpha \sim Normal(0,10)$</li>
<li>$\beta \sim Normal(0,1)$</li>
<li>$\sigma \sim Uniform(0,10)$</li>
</ol>
<p><strong>Answer:</strong> The linear model is <em>deterministic</em> in nature (i.e. the parameters determine the value of the response variable). This is identified with the mathematical notation of $=$. Therefore, line 2. $\mu_i=\alpha+\beta x_i$ is the linear model. All other specifications are <em>stochastic</em> links (identified with $\sim$).</p>
<h3 id="practice-e5">Practice E5</h3>
<p><strong>Question:</strong> In the model definition just above, how many parameters are in the posterior distribution?</p>
<p><strong>Answer:</strong> Three. $\alpha$, $\beta$, and $\sigma$ are the parameters we estimate. $y_i \sim Normal(\mu, \sigma)$ is the likelihood.</p>
<h2 id="medium-exercises">Medium Exercises</h2>
<p>This is where we get into <code>R</code> applications.</p>
<pre><code class="language-r">rm(list = ls())
library(rethinking)
</code></pre>
<h3 id="practice-m1">Practice M1</h3>
<p><strong>Question:</strong> For the model definition below, simulate observed heights from the prior (not the posterior).</p>
<ol>
<li>$y_i \sim Normal(\mu, \sigma)$</li>
<li>$\mu \sim Normal(0, 10)$</li>
<li>$\sigma \sim Uniform(0, 10)$</li>
</ol>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">set.seed(42)
sample_mu &lt;- rnorm(1e4, 0, 10)
sample_sigma &lt;- runif(1e4, 0, 10)
prior_y &lt;- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_y)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-2-1.png" width="1440" /></p>
<h3 id="practice-m2">Practice M2</h3>
<p><strong>Question:</strong> Translate the model just above into a <code>quap()</code> formula.</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">formula &lt;- alist(
  y ~ dnorm(mu, sigma),
  mu ~ dnorm(0, 10),
  sigma ~ dunif(0, 10)
)
formula
</code></pre>
<pre><code>## [[1]]
## y ~ dnorm(mu, sigma)
## 
## [[2]]
## mu ~ dnorm(0, 10)
## 
## [[3]]
## sigma ~ dunif(0, 10)
</code></pre>
<h3 id="practice-m3">Practice M3</h3>
<p><strong>Question:</strong> Translate the <code>quap()</code> model formula below into a mathematical model definition.</p>
<pre><code class="language-r">flist &lt;- alist(
  y ~ dnorm(mu, sigma),
  mu &lt;- a + b * x,
  a ~ dnorm(0, 50),
  b ~ dunif(0, 10),
  sigma ~ dunif(0, 50)
)
</code></pre>
<p><strong>Answer:</strong></p>
<ol>
<li>$y_i \sim Normal(\mu, \sigma)$</li>
<li>$\mu_i=\alpha+\beta x_i$</li>
<li>$\alpha \sim Normal(0,50)$</li>
<li>$\beta \sim Uniform(0,10)$</li>
<li>$\sigma \sim Uniform(0,50)$</li>
</ol>
<h3 id="practice-m4">Practice M4</h3>
<p><strong>Question:</strong> A sample of students is measured for height each year for 3 years. After the third year, you want to fit a linear regression predicting height using year as a predictor. Write down the mathematical model definition for this regression, using any variable names and priors you choose. Be prepared to defend you choice of priors.</p>
<p><strong>Answer:</strong> Firstly, I start by identifying the likelihood of heights $h$. I assume these to be normally distributed around some mean $\mu$, with a standard deviation of $\sigma$:</p>
<p>$h_i = Normal(\mu, \sigma)$</p>
<p>$\mu$ is the mean of heights and can be obtained as follows:</p>
<p>$\mu_i = \alpha + \beta x_i$</p>
<p>Setting aside the issue of independence here - each student shows up in the data multiple times, thus making the time-series of heights dependent and potentially autocorrelated - no age range has been specified for our students in question. This leaves us with little information regarding potential priors (elementary school students are much smaller than university students). Therefore, I chose a weak prior with a large range. I call this prior for the height intercept $\alpha$ and assume a normal distribution with a wide range:</p>
<p>$\alpha \sim Normal(150,25)$</p>
<pre><code class="language-r">set.seed(42)
dens(rnorm(1e4, 150, 25))
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-5-1.png" width="1440" /></p>
<p>$\beta$ represents the average increase of in height for each year. Again, the potentially large age range means we have to use a somewhat uninformative prior because people grow very differently at different ages. The distribution here could be argued to be uniform or normal. I am going with normal because it emphasises a much more peaked distribution of growth rates with an emphasis for the mean:</p>
<p>$\beta \sim Normal(4,1)$</p>
<pre><code class="language-r">set.seed(42)
dens(rnorm(1e4, 4, 2))
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-6-1.png" width="1440" /></p>
<p>As you can see, this choice of prior for $\alpha$ would allow for negative growth rates which might be an issue.</p>
<p>Finally, we need to identify our $\sigma$ where I specify a uniform range that covers the full range of heights when given a large range of students (in age, that is):</p>
<p>$\sigma \sim Uniform(0,30)$</p>
<p>Plugging this one into our height simulation, we get a wide but overall sensible range:</p>
<pre><code class="language-r">set.seed(42)
dens(rnorm(1e4, 150, 30))
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-7-1.png" width="1440" /></p>
<p>Personally, I think a second-order polynomial regression could be sensible here to account for the change in growth rate over time, but I assume a latter question will deal with that.</p>
<h3 id="practice-m5">Practice M5</h3>
<p><strong>Question:</strong> Now suppose I remind you that every student got taller each year. Does this information lead you to change your choice of priors? How?</p>
<p><strong>Answer:</strong> Yes, I can change my prior for $\beta$ to always be positive by using a log-normal distribution:</p>
<p>$\beta \sim LogNormal(2,0.5)$</p>
<pre><code class="language-r">set.seed(42)
dens(rlnorm(1e4, 2, .5))
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-8-1.png" width="1440" />
Now this makes much more sense!</p>
<!-- ## Practice M6 -->
<!-- **Question:** Now suppose I tell you that the average height in the first year was 120 cm and that every student got taller each year. Does this information lead you to change your choice of priors? How?   -->
<!-- **Answer:** This really changes things. We now know that we are talking about school-age students (around 6-8 years of age). This means we can alter our priors quite significantly as follows:   -->
<!-- $\alpha$ - We know the average height to be 120cm, and can set a relatively small standard deviation on that distribution:   -->
<!-- $\alpha \sim Normal(150,25)$   -->
<!-- $\beta$ - We know that children this age grow much faster than older people and so can increase our prior for this with more certainty:   -->
<!-- $\beta \sim Normal(7,1)$ -->
<!-- $\sigma$ - this is the standard deviation of the overall height likelihood function. We can make this more conservative, knowing that we have a tighter age range: -->
<!-- $\sigma \sim Uniform(0,20)$ -->
<h3 id="practice-m6">Practice M6</h3>
<p><strong>Question:</strong> Now suppose I tell you that the variance among heights for students of the same age is never more than 64 cm. How does this lead you to revise your priors?</p>
<p><strong>Answer:</strong> The variance is the square product of $\sigma$, so we know that $\sigma$ never exceeds $\sqrt(64) = 8$ and can update our prior accordingly:</p>
<p>$\sigma \sim Uniform(0,8)$</p>
<pre><code class="language-r">set.seed(42)
dens(runif(1e4, 0, 8))
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-9-1.png" width="1440" /></p>
<h2 id="hard-exercises">Hard Exercises</h2>
<h3 id="practice-h1">Practice H1</h3>
<p><strong>Question:</strong> The weights listed below were recorded in the !Kung census, but heights were not recorded for these individuals. Provide predicted heights and 89% intervals (either HPDI or PI) for each of these individuals. That is, fill in the table below, using model-based predictions.</p>
<table>
<thead>
<tr>
<th>Individual</th>
<th style="text-align:center">weight</th>
<th style="text-align:center">expected height</th>
<th style="text-align:center">89% interval</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td style="text-align:center">46.95</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
<tr>
<td>2</td>
<td style="text-align:center">43.72</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
<tr>
<td>3</td>
<td style="text-align:center">64.78</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
<tr>
<td>4</td>
<td style="text-align:center">32.59</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
<tr>
<td>5</td>
<td style="text-align:center">54.63</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">data(&quot;Howell1&quot;)
d &lt;- Howell1
formula &lt;- alist(
  height ~ dnorm(mu, sigma),
  mu &lt;- a + b * weight,
  a ~ dnorm(150, 30), # a relatively short height with a large SD to account for large age spread in data set and the overall smaller stature of the peoples in the !Kung census
  b ~ dlnorm(0, 1), # I want strictly positive weight-height relationships
  sigma ~ dunif(0, 50) # rather large SD
)
(m &lt;- quap(formula, data = d))
</code></pre>
<pre><code>## 
## Quadratic approximate posterior distribution
## 
## Formula:
## height ~ dnorm(mu, sigma)
## mu &lt;- a + b * weight
## a ~ dnorm(150, 30)
## b ~ dlnorm(0, 1)
## sigma ~ dunif(0, 50)
## 
## Posterior means:
##         a         b     sigma 
## 75.550586  1.761449  9.345982 
## 
## Log-likelihood: -1987.71
</code></pre>
<p>Now, we can obtain the posterior distributions for our weight values in the table:</p>
<pre><code class="language-r">new_weight &lt;- c(46.95, 43.72, 64.78, 32.59, 54.63)
pred_height &lt;- link(m, data = data.frame(weight = new_weight))
expected &lt;- apply(pred_height, 2, mean)
interval &lt;- apply(pred_height, 2, HPDI, prob = 0.89)
</code></pre>
<p>Finally, we merge this into a data frame:</p>
<pre><code class="language-r">data.frame(
  individual = 1:5,
  weight = new_weight,
  expected = expected,
  lower = interval[1, ],
  upper = interval[2, ]
)
</code></pre>
<pre><code>##   individual weight expected    lower    upper
## 1          1  46.95 158.2948 157.4868 159.1242
## 2          2  43.72 152.6012 151.9167 153.3826
## 3          3  64.78 189.7242 188.3729 191.2549
## 4          4  32.59 132.9821 132.3565 133.6889
## 5          5  54.63 171.8326 170.9136 173.0242
</code></pre>
<h3 id="practice-h2">Practice H2</h3>
<p><strong>Question:</strong> Select out all the rows in the Howell1 data with ages below 18 years of age. If you do it right, you should end up with a new data frame with 192 rows in it.</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">d2 &lt;- Howell1[Howell1$age &lt; 18, ]
weight_bar &lt;- mean(d2$weight)
nrow(d2)
</code></pre>
<pre><code>## [1] 192
</code></pre>
<h4 id="part-a">Part A</h4>
<p><strong>Question:</strong> Fit a linear regression to these data, using <code>quap()</code>. Present and interpret the estimates. For every 10 units of increase in weight, how much taller does the model predict a child gets?</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">formula &lt;- alist(
  height ~ dnorm(mu, sigma),
  mu &lt;- a + b * (weight - weight_bar),
  a ~ dnorm(110, 30),
  b ~ dlnorm(0, 1),
  sigma ~ dunif(0, 60)
)
m &lt;- quap(formula, data = d2)
precis(m)
</code></pre>
<pre><code>##             mean        sd       5.5%      94.5%
## a     108.319563 0.6087746 107.346624 109.292503
## b       2.716656 0.0683154   2.607475   2.825838
## sigma   8.437165 0.4305635   7.749042   9.125289
</code></pre>
<p>For a 10-unit increase in weight, we see a 27.17cm increase in height.</p>
<h4 id="part-b">Part B</h4>
<p><strong>Question:</strong> Plot the raw data, with height on the vertical axis and weight on the horizontal axis. Superimpose the MAP regression line and 89% HPDI for the mean. Also superimpose the 89% HPDI for predicted heights.</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r"># Data for plot
weight.seq &lt;- seq(from = min(d2$weight), to = max(d2$weight), by = 1) # sequence to do predictions for
mu &lt;- link(m, data = data.frame(weight = weight.seq)) # do predictions
mu.mean &lt;- apply(mu, 2, mean) # calculate mean
mu.HPDI &lt;- apply(mu, 2, HPDI, prob = 0.89) # identify interval
sim.height &lt;- sim(m, data = list(weight = weight.seq)) # simulate full predictions
height.HPDI &lt;- apply(sim.height, 2, HPDI, prob = 0.89) # identify interval

# Plotting
plot(height ~ weight, data = d2, col = col.alpha(rangi2, 0.7)) # base plot
lines(weight.seq, mu.mean) # add mean line
shade(mu.HPDI, weight.seq) # add hdpi interval
shade(height.HPDI, weight.seq) # add full-hdpi interval
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-15-1.png" width="1440" /></p>
<h4 id="part-c">Part C</h4>
<p><strong>Question:</strong> What aspects of the model fit concern you? Describe the kinds of assumptions you would change, if any, to improve the model. You don’t have to write any new code. Just explain what the model appears to be doing a bad job of, and what you hypothesize would be a better model.</p>
<p><strong>Answer:</strong> The model woefully overpredicts height at the low-weight end of the spectrum as well as the upper end of the weight spectrum. At the mid-range of the weight spectrum, our model underpredicts height. It looks as though the data fall onto a curve and so we could potentially do better with a polynomial model.</p>
<h3 id="practice-h3">Practice H3</h3>
<p><strong>Question:</strong> Suppose a colleague of yours, who works on allometry, glances at the practice problems just above. Your colleague exclaims, “That’s silly. Everyone knows that it’s only the logarithm of body weight that scales with height!” Let’s take your colleague’s advice and see what happens.</p>
<h4 id="part-a-1">Part A</h4>
<p><strong>Question:</strong> Model the relationship between height (cm) and the natural logarithm of weight (log-kg). Use the entire Howell1 data frame, all 544 rows, adults and non-adults. Fit this model, using the quadratic approximation:</p>
<p>$h_i ∼ Normal(\mu_i, \sigma)$<br>
$\mu_i = \alpha + \beta log(w_i)$<br>
$\alpha ∼ Normal(178, 20)$<br>
$\beta ∼ LogNormal(0, 1)$<br>
$\sigma ∼ Uniform(0, 50)$</p>
<p>where $h_i$ is the height of individual $i$ and $w_i$ is the weight (in kg) of individual $i$. The function for computing a natural log in <code>R</code> is just <code>log()</code>. Can you interpret the resulting estimates?</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">d &lt;- Howell1
formula &lt;- alist(
  height ~ dnorm(mu, sigma),
  mu &lt;- a + b * log(weight),
  a ~ dnorm(178, 20),
  b ~ dlnorm(0, 1),
  sigma ~ dunif(0, 50)
)
m &lt;- quap(formula, data = d)
precis(m)
</code></pre>
<pre><code>##             mean        sd       5.5%      94.5%
## a     -22.874329 1.3343120 -25.006817 -20.741840
## b      46.817801 0.3823300  46.206764  47.428838
## sigma   5.137168 0.1558908   4.888025   5.386312
</code></pre>
<p>Our $\alpha$ estimate seems to be out-of-line at -22.87. This is simply the predicted height when the weight is 0 log-kg and thus somewhat uninformative. $\beta$ tells us that our individual grow, on average, by 46.82cm per increase in log-kg by 1. The standard deviation around our height predictions is 5.14.</p>
<p>Transforming a variable makes interpreting diffuclt.</p>
<h4 id="part-b-1">Part B</h4>
<p><strong>Question:</strong> Begin with this plot: <code>plot(height ~ weight, data = Howell1), col = col.alpha(rangi2, 0.4))</code>. Then use samples from the quadratic approximate posterior of the model in (a) to superimpose on the plot: (1) the predicted mean height as a function of weight, (2) the 97% HPDI for the mean, and (3) the 97% HPDI for predicted heights.</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">plot(height ~ weight, data = d, col = col.alpha(rangi2, 0.4))
# Estimate and plot the quap regression line and 97% HPDI for the mean
weight.seq &lt;- seq(from = min(d$weight), to = max(d$weight), by = 1)
mu &lt;- link(m, data = data.frame(weight = weight.seq))
mu.mean &lt;- apply(mu, 2, mean)
mu.HPDI &lt;- apply(mu, 2, HPDI, prob = 0.97)
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
# Estimate and plot the 97% HPDI for the predicted heights
sim.height &lt;- sim(m, data = list(weight = weight.seq))
height.HPDI &lt;- apply(sim.height, 2, HPDI, prob = 0.97)
shade(height.HPDI, weight.seq)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-17-1.png" width="1440" />
Yup, this does fit much more neatly.</p>
<h3 id="practice-h4">Practice H4</h3>
<p><strong>Question:</strong> Plot the prior predictive distribution for the polynomial regression model in the chapter. You can modify the code that plots the linear regression prior predictive distribution. Can you modify the prior distributions of $\alpha$, $\beta_1$, and $\beta_2$ so that the prior predictions stay within the biologically reasonable outcome space? That is to say: Do not try to fit the data by hand. But do try to keep the curves consistent with what you know about height and weight, before seeing these exact data.</p>
<p><strong>Answer:</strong></p>
<pre><code class="language-r">data(&quot;Howell1&quot;)
d &lt;- Howell1
# standardising weight
d$weight_s &lt;- with(d, (weight - mean(weight)) / sd(weight))
# quadratic weight
d$weight_s2 &lt;- d$weight_s^2

# MODEL
M_Poly &lt;- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu &lt;- a + b1 * weight_s + b2 * weight_s2,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = d
)
precis(M_Poly)
</code></pre>
<pre><code>##             mean        sd       5.5%      94.5%
## a     146.054799 0.3689900 145.465082 146.644517
## b1     21.734548 0.2888949  21.272839  22.196258
## b2     -7.800570 0.2742037  -8.238800  -7.362339
## sigma   5.774487 0.1764685   5.492456   6.056517
</code></pre>
<p>The prior prediction can be obtained using <code>extract.prior()</code>. The obtained sample can then be passed on to the <code>link()</code> function for the weight space in question. Since we want to try multiple priors, I use a function that takes the <code>alist</code> object as well as the number of predicted curves as arguments. This function-idea has been adapted from 
<a href="https://gregor-mathes.netlify.app/2021/01/01/rethinking-chapter-4/#question-4m5" target="_blank" rel="noopener">Gregor Mathes</a> solution which is based on the use of <code>tidyverse</code>:</p>
<pre><code class="language-r">library(tidyr) # we don't get around using the function pivot_longer()
library(ggplot2)
modify_prior_poly &lt;- function(my_alist, N) {
  # set seed for reproducibility
  set.seed(42)
  # fit model
  m_poly &lt;- quap(my_alist, data = d)
  # make weight sequence with both standardised weight and the square of it
  weight_seq &lt;- seq(from = min(d$weight), to = max(d$weight), by = 1)
  weight_seq &lt;- data.frame(
    weight = weight_seq,
    weight_s = (weight_seq - mean(weight_seq)) / sd(weight_seq),
    weight_s2 = ((weight_seq - mean(weight_seq)) / sd(weight_seq))^2
  )
  # extract samples from the prior
  m_poly_prior &lt;- extract.prior(m_poly, n = N)
  # now apply the polynomial equation to the priors to get predicted heights
  m_poly_mu &lt;- link(
    m_poly,
    post = m_poly_prior,
    data = list(
      weight_s = weight_seq$weight_s,
      weight_s2 = weight_seq$weight_s2
    )
  )
  m_poly_mu &lt;- as.data.frame(m_poly_mu)
  m_poly_mu &lt;- as.data.frame(pivot_longer(m_poly_mu, cols = everything(), values_to = &quot;height&quot;))
  m_poly_mu$weight &lt;- rep(weight_seq$weight, N)
  m_poly_mu$type &lt;- rep(as.character(1:N), each = length(weight_seq$weight))
  # plot it
  ggplot(m_poly_mu) +
    geom_line(aes(x = weight, y = height, group = type), alpha = 0.5) +
    geom_hline(yintercept = c(0, 272), colour = &quot;steelblue4&quot;) +
    annotate(
      geom = &quot;text&quot;,
      x = c(6, 12),
      y = c(11, 285),
      label = c(&quot;Embryo&quot;, &quot;World's tallest person&quot;),
      colour = c(rep(&quot;steelblue4&quot;, 2))
    ) +
    labs(x = &quot;Weight in kg&quot;, y = &quot;Height in cm&quot;) +
    theme_minimal()
}
</code></pre>
<p>Let&rsquo;s run this for our initial model specification:</p>
<pre><code class="language-r">modify_prior_poly(
  my_alist = alist(
    height ~ dnorm(mu, sigma),
    mu &lt;- a + b1 * weight_s + b2 * weight_s2,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  N = 40
)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-20-1.png" width="1440" /></p>
<p>The priors should cover the whole biologically sensible space (unless we have some really strong indication for this not being the case). Let&rsquo;s start by decreasing the mean for $\alpha$ and increasing its standard deviation:</p>
<pre><code class="language-r">modify_prior_poly(
  my_alist = alist(
    height ~ dnorm(mu, sigma),
    mu &lt;- a + b1 * weight_s + b2 * weight_s2,
    a ~ dnorm(130, 35), # decrease mean and increase sd
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  N = 40
)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-21-1.png" width="1440" /></p>
<p>Better, but not quite there yet. The lines themselves could do with stronger positive relationship here between weight and height. We know this relationship to be stronger:</p>
<pre><code class="language-r">modify_prior_poly(
  my_alist = alist(
    height ~ dnorm(mu, sigma),
    mu &lt;- a + b1 * weight_s + b2 * weight_s2,
    a ~ dnorm(130, 35),
    b1 ~ dlnorm(1, 1), # increase mean, but not sd (we don't want negative relationships)
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  N = 40
)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-22-1.png" width="1440" /></p>
<p>I am already happy with this. However, we can see some downward curving weight-height relationships here. That&rsquo;s probably not what we find in the real-world and so we might want to force these relationships to always curve upwards, by having a positive $\beta_2$ with a narrow log-normal distribution:</p>
<pre><code class="language-r">modify_prior_poly(
  my_alist = alist(
    height ~ dnorm(mu, sigma),
    mu &lt;- a + b1 * weight_s + b2 * weight_s2,
    a ~ dnorm(130, 35),
    b1 ~ dlnorm(1, 1),
    b2 ~ dlnorm(0, .05), # force positive parameter
    sigma ~ dunif(0, 50)
  ),
  N = 40
)
</code></pre>
<p><img src="2021-01-08-statistical-rethinking-chapter-04_files/figure-html/unnamed-chunk-23-1.png" width="1440" /></p>
<p>Phew. I can&rsquo;t think of more, to be honest. This looks good to me.</p>
<h2 id="session-info">Session Info</h2>
<pre><code class="language-r">sessionInfo()
</code></pre>
<pre><code>## R version 4.0.5 (2021-03-31)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19043)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
## [5] LC_TIME=English_United Kingdom.1252    
## 
## attached base packages:
## [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] tidyr_1.1.3          rethinking_2.13      rstan_2.21.2         ggplot2_3.3.3        StanHeaders_2.21.0-7
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.7         mvtnorm_1.1-1      lattice_0.20-41    prettyunits_1.1.1  ps_1.6.0           assertthat_0.2.1   digest_0.6.27      utf8_1.2.1         V8_3.4.1           R6_2.5.0          
## [11] backports_1.2.1    stats4_4.0.5       evaluate_0.14      coda_0.19-4        highr_0.9          blogdown_1.3       pillar_1.6.0       rlang_0.4.11       curl_4.3.2         callr_3.7.0       
## [21] jquerylib_0.1.4    R.utils_2.10.1     R.oo_1.24.0        rmarkdown_2.7      styler_1.4.1       labeling_0.4.2     stringr_1.4.0      loo_2.4.1          munsell_0.5.0      compiler_4.0.5    
## [31] xfun_0.22          pkgconfig_2.0.3    pkgbuild_1.2.0     shape_1.4.5        htmltools_0.5.1.1  tidyselect_1.1.0   tibble_3.1.1       gridExtra_2.3      bookdown_0.22      codetools_0.2-18  
## [41] matrixStats_0.61.0 fansi_0.4.2        crayon_1.4.1       dplyr_1.0.5        withr_2.4.2        MASS_7.3-53.1      R.methodsS3_1.8.1  grid_4.0.5         jsonlite_1.7.2     gtable_0.3.0      
## [51] lifecycle_1.0.0    DBI_1.1.1          magrittr_2.0.1     scales_1.1.1       RcppParallel_5.1.2 cli_3.0.0          stringi_1.5.3      farver_2.1.0       bslib_0.2.4        ellipsis_0.3.2    
## [61] generics_0.1.0     vctrs_0.3.7        rematch2_2.1.2     tools_4.0.5        R.cache_0.14.0     glue_1.4.2         purrr_0.3.4        processx_3.5.1     yaml_2.2.1         inline_0.3.17     
## [71] colorspace_2.0-0   knitr_1.33         sass_0.3.1
</code></pre>

          </div>

          

<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/statistics/">Statistics</a>
  
  <a class="badge badge-light" href="/tag/bayesian-statistics/">Bayesian Statistics</a>
  
  <a class="badge badge-light" href="/tag/bayes/">Bayes</a>
  
  <a class="badge badge-light" href="/tag/au-bayes-study-group/">AU Bayes Study Group</a>
  
</div>



          
          <div class="article-widget">
            
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/courses/rethinking/chapter-03/" rel="next">Chapter 03</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/courses/rethinking/chapter-04b/" rel="prev">Chapter 04 (Extra Material)</a>
  </div>
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          <p>Last updated on 2021-01-08</p>

          





          


          


  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/courses/rethinking/chapter-16/">Chapter 16</a></li>
      
      <li><a href="/courses/rethinking/chapter-15/">Chapter 15</a></li>
      
      <li><a href="/courses/rethinking/chapter-14/">Chapter 14</a></li>
      
      <li><a href="/courses/rethinking/chapter-13/">Chapter 13</a></li>
      
      <li><a href="/courses/rethinking/chapter-12/">Chapter 12</a></li>
      
    </ul>
  </div>
  



        </div>

      </article>

      <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
    
  </p>
  

  <p class="powered-by">
    © 2024
  </p>

  
  






  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
  </p>
</footer>


    </main>
  </div>
</div>


      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/latex.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.66c553246b0f279a03be6e5597f72b52.js"></script>

    






  
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
