<!DOCTYPE html><html lang="en-gb" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Erik Kusch">

  
  
  
    
  
  <meta name="description" content="Welcome to our first &#34;real&#34; practical experience in `R`. The following notes present you with an example of how data handling (also known as data cleaning) can be done. Obviously, the possibility for flaws to occur in any given data set are seemingly endless and so the following, tedious procedure should be thought of as less of an recipe of how to fix common flaws in biological data sets but make you aware of how important proper data collection and data entry is.">

  
  <link rel="alternate" hreflang="en-gb" href="https://www.erikkusch.com/courses/an-introduction-to-biostatistics/data-handling-and-data-mining/">

  


  
  
  
  <meta name="theme-color" content="#858383">
  

  
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      
        
      

      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cutive+Mono%7CLora:400,700%7CRoboto:400,700&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-186216138-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-186216138-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://www.erikkusch.com/courses/an-introduction-to-biostatistics/data-handling-and-data-mining/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@ErikKusch">
  <meta property="twitter:creator" content="@ErikKusch">
  
  <meta property="og:site_name" content="Erik Kusch">
  <meta property="og:url" content="https://www.erikkusch.com/courses/an-introduction-to-biostatistics/data-handling-and-data-mining/">
  <meta property="og:title" content="Data Handling and Data Mining | Erik Kusch">
  <meta property="og:description" content="Welcome to our first &#34;real&#34; practical experience in `R`. The following notes present you with an example of how data handling (also known as data cleaning) can be done. Obviously, the possibility for flaws to occur in any given data set are seemingly endless and so the following, tedious procedure should be thought of as less of an recipe of how to fix common flaws in biological data sets but make you aware of how important proper data collection and data entry is."><meta property="og:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg">
  <meta property="twitter:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg"><meta property="og:locale" content="en-gb">
  
    
      <meta property="article:published_time" content="2020-06-10T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-06-10T00:00:00&#43;00:00">
  

  



  


  


  





  <title>Data Handling and Data Mining | Erik Kusch</title>

</head>
<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  








  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-center" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/"><span>Home</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Courses & Workshops</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/courses/krigr/"><span>KrigR - State-of-the-Art Climate Data within R</span></a>
            
              <a class="dropdown-item" href="/courses/gbif/"><span>Accessing and Referencing GBIF Data for Research</span></a>
            
              <a class="dropdown-item" href="/courses/rethinking/"><span>Statistical Rethinking - Introduction to Bayesian Statistics</span></a>
            
              <a class="dropdown-item" href="/courses/bayes-nets/"><span>Bayesian Networks - Causality through Bayesian Approaches</span></a>
            
              <a class="dropdown-item" href="/courses/biostat101/"><span>Biostats 101 - An Introduction to Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/excursions-into-biostatistics/"><span>Biostats 301 - Excursions into Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/bftp-biome-detection/"><span>BFTP - First Steps in Macroecology in R</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/about"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://htmlpreview.github.io/?https://github.com/ErikKusch/Homepage/blob/master/static/media/CV_ErikKusch.html" target="_blank" rel="noopener"><span>CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  

<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
  <input name="q" type="search" class="form-control" placeholder="Search..." autocomplete="off">
  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/an-introduction-to-biostatistics/">Overview</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/an-introduction-to-biostatistics/01-an-introduction-to-basic-statistics-for-biologists/">Sessions</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/01-an-introduction-to-basic-statistics-for-biologists/">01 - Basic Statistics for Biologists</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/introduction-to-r/">02 - Introduction to R</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/a-primer-for-statistical-tests/">03 - A Primer For Statistical Tests</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/descriptive-statistics/">04 - Descriptive Statistics</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/data-visualisation/">05 - Data Visualisation</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/06-inferential-statistics-hypotheses-and-our-research-project/">06 - Inferential Statistics, Hypotheses And Our Research Project</a>
      </li>
      
      <li class="active">
        <a href="/courses/an-introduction-to-biostatistics/data-handling-and-data-mining/">07 - Data Handling and Data Mining</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/nominal-tests/">08 - Nominal Tests</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/correlation-tests/">09 - Correlation Tests</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/ordinal-metric-tests-two-sample-situations/">10 - Ordinal &amp; Metric Tests (Two-Sample Situations)</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/ordinal-metric-tests-more-than-two-sample-situations/">11 - Ordinal &amp; Metric Tests (More-Than-Two-Sample Situations)</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/simple-parametric-tests/">12 - Simple Parametric Tests</a>
      </li>
      
      <li >
        <a href="/courses/an-introduction-to-biostatistics/13-an-outlook-on-advanced-statistics/">13 - Closing &amp; Summary</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

    </div>

    
    <div class="d-none d-xl-block col-xl-2 docs-toc">
      <ul class="nav toc-top">
        <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
      </ul>

      <nav id="TableOfContents">
  <ul>
    <li><a href="#theory">Theory</a></li>
    <li><a href="#data">Data</a></li>
    <li><a href="#preparing-our-procedure">Preparing Our Procedure</a>
      <ul>
        <li><a href="#necessary-steps-for-reproducibility">Necessary Steps For Reproducibility</a></li>
        <li><a href="#packages">Packages</a></li>
        <li><a href="#loading-the-data">Loading The Data</a></li>
      </ul>
    </li>
    <li><a href="#inspecting-the-data">Inspecting The Data</a>
      <ul>
        <li><a href="#assessing-a-data-frame-in-r">Assessing A Data Frame in <code>R</code></a></li>
        <li><a href="#the-summary-function">The <code>Summary()</code> Function</a></li>
      </ul>
    </li>
    <li><a href="#data-cleaning-workflow">Data Cleaning Workflow</a>
      <ul>
        <li><a href="#identifying-problems">Identifying Problems</a></li>
        <li><a href="#fixing-the-problems">Fixing The Problems</a></li>
      </ul>
    </li>
    <li><a href="#our-data">Our Data</a>
      <ul>
        <li><a href="#site">Site</a></li>
        <li><a href="#index">Index</a></li>
        <li><a href="#latitude">Latitude</a></li>
        <li><a href="#longitude">Longitude</a></li>
        <li><a href="#climate">Climate</a></li>
        <li><a href="#population-status">Population Status</a></li>
        <li><a href="#weight">Weight</a></li>
        <li><a href="#height">Height</a></li>
        <li><a href="#wing-chord">Wing Chord</a></li>
        <li><a href="#colour">Colour</a></li>
        <li><a href="#sex">Sex</a></li>
        <li><a href="#nesting-site">Nesting Site</a></li>
        <li><a href="#nesting-height">Nesting Height</a></li>
        <li><a href="#number-of-eggs">Number of Eggs</a></li>
        <li><a href="#egg-weight">Egg Weight</a></li>
        <li><a href="#flock">Flock</a></li>
        <li><a href="#home-range">Home Range</a></li>
        <li><a href="#flock-size">Flock Size</a></li>
        <li><a href="#predator-presence">Predator Presence</a></li>
        <li><a href="#predator-type">Predator Type</a></li>
        <li><a href="#redundant-data">Redundant Data</a></li>
      </ul>
    </li>
    <li><a href="#saving-the-fixed-data-set">Saving The Fixed Data Set</a>
      <ul>
        <li><a href="#final-check">Final Check</a></li>
        <li><a href="#exporting-the-altered-data">Exporting The Altered Data</a></li>
      </ul>
    </li>
  </ul>
</nav>

      
    </div>
    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

      <article class="article">

        <div class="docs-article-container">
          <h1>Data Handling and Data Mining</h1>

          <div class="article-style">
            <h2 id="theory">Theory</h2>
<p>Welcome to our first &ldquo;real&rdquo; practical experience in <code>R</code>. The following notes present you with an example of how data handling (also known as data cleaning) can be done. Obviously, the possibility for flaws to occur in any given data set are seemingly endless and so the following, tedious procedure should be thought of as less of an recipe of how to fix common flaws in biological data sets but make you aware of how important proper data collection and data entry is.</p>
<p>I have prepared some <a href="/courses/an-introduction-to-biostatistics/07---Data-Handling-and-Data-Mining_Handout.html" target="_blank"> Lecture Slides </a> for this session.</p>
<h2 id="data">Data</h2>
<p>Find the data for this exercise <a href="/courses/an-introduction-to-biostatistics/Data/SparrowData.csv" target="_blank"> here</a>.</p>
<h2 id="preparing-our-procedure">Preparing Our Procedure</h2>
<p>The following three sections are what I consider to be <em>essential</em> parts of the preamble to any <code>R</code>-based analysis. I highly recommend clearly indicating these bits in your code.</p>
<p>More often than not, you will use variations of these code chunks whether you are working on data handling, data exploration or full-fledged statistical analyses.</p>
<h3 id="necessary-steps-for-reproducibility">Necessary Steps For Reproducibility</h3>
<p>Reproducibility is the be-all and end-all of any statistical analysis, particularly in light of the peer-review process in life sciences.</p>
<pre><code class="language-r">rm(list=ls()) # clearing environment
Dir.Base &lt;- getwd() # soft-coding our working directory
Dir.Data &lt;- paste(Dir.Base, &quot;Data&quot;, sep=&quot;/&quot;) # soft-coding our data directory 
</code></pre>
<p>Once you get into highly complex statistical analyses, you may wish to break up chunks of your analysis into separate documents. To ensure that remnants of an earlier analysis or analysis chunk do not influence the results of your current analysis, you may wish to <em>empty</em> <code>R</code>&rsquo;s cache (<em>Environment</em>) before attempting a new analysis. This is achieved via the command <code>rm(list=ls())</code>.</p>
<p>Next, you <em>need</em> to remember the importance of <em>soft-coding</em> for the sake of reproducibility. One of the worst offences to the peer-review process in <code>R</code>-based statistics is the erroneous hard-coding of the working directory. The <code>getwd()</code> function shown above solves this exact problem. However, for this workaround to function properly you need to open the code document of interest by double-clicking it within its containing folder.</p>
<p>When using the <code>xlsx</code> package or any <em>Excel</em>-reliant process via <code>R</code>, your code will automatically run a Java process in the background. By default the Java engine is limited as far as RAM allocation goes and tends to fail when faced with enormous data sets. The workaround <code>options(java.parameters = &quot;-Xmx8g&quot;)</code> gets rid of this issue by allocation 8 GBs of RAM to Java.</p>
<h3 id="packages">Packages</h3>
<p>Packages are <code>R</code>&rsquo;s way of giving you access to a seemingly infinite repository of functions.</p>
<pre><code class="language-r"># function to load packages and install them if they haven't been installed yet
install.load.package &lt;- function(x) {
  if (!require(x, character.only = TRUE))
    install.packages(x)
  require(x, character.only = TRUE)
}
package_vec &lt;- c(&quot;dplyr&quot; # we need this package to fix the most common data errors
                 )
sapply(package_vec, install.load.package)
</code></pre>
<pre><code>## Loading required package: dplyr
</code></pre>
<pre><code>## 
## Attaching package: 'dplyr'
</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag
</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre>
<pre><code>## dplyr 
##  TRUE
</code></pre>
<p>Using the above function is way more sophisticated than the usual <code>install.packages()</code> + <code>library()</code> approach since it automatically detects which packages require installing and only install these thus not overwriting already installed packages.</p>
<h3 id="loading-the-data">Loading The Data</h3>
<p>Loading data is crucial to any analysis in <code>R</code>. Period.</p>
<p><code>R</code> offers a plethora of approaches to data loading and you will usually be taught the <code>read.table()</code> command in basic biostatistics courses. However, I have found to prefer the functionality provided by the <code>xlsx</code> package since most data recording is taking place in Excel. As this package is dependant on the installation of Java and <code>RJava</code>, we will settle on the base <code>R</code> function <code>read.csv()</code>.</p>
<pre><code class="language-r">Data_df_base &lt;- read.csv(file = paste(Dir.Data, &quot;/SparrowData.csv&quot;, sep=&quot;&quot;), header = TRUE)
Data_df &lt;- Data_df_base # duplicate and save initial data on a new object
</code></pre>
<p>Another trick to have up your sleeve (if your RAM enables you to act on it) is to duplicate your initial data onto a new object once loaded into <code>R</code>. This will enable you to easily remedy mistakes in data treatment without having to reload your initial data set from the data file.</p>
<h2 id="inspecting-the-data">Inspecting The Data</h2>
<p>Once the data is loaded into <code>R</code>, you <em>need to inspect</em> it to make sure it is ready for use.</p>
<h3 id="assessing-a-data-frame-in-r">Assessing A Data Frame in <code>R</code></h3>
<p>Most, if not all, data you will ever load into <code>R</code> will be stored as a <code>data.frame</code> within <code>R</code>. Some of the most important functions for inspecting data frames (&ldquo;df&rdquo; in the following) in base <code>R</code> are the following four:</p>
<ul>
<li><code>dim(df)</code> returns the dimensions (Rows $\times$ Columns)of the data frame</li>
<li><code>head(df)</code> returns the first 6 rows of the data frame by default (here changed to 4)</li>
<li><code>tail(df)</code> returns the last 6 rows of the data frame by default (here changed to 4)</li>
<li><code>View(df)</code> opens nearly any <code>R</code> object in a separate tab for further inspection. Since we are dealing with an enormous data set here, I will exclude this function for now to save you from printing unnecessary pages.</li>
</ul>
<pre><code class="language-r">dim(Data_df)
</code></pre>
<pre><code>## [1] 1068   21
</code></pre>
<pre><code class="language-r">head(Data_df, n = 4)
</code></pre>
<pre><code>##   X    Site Index Latitude Longitude     Climate Population.Status Weight
## 1 1 Siberia    SI       60       100 Continental            Native  34,05
## 2 2 Siberia    SI       60       100 Continental            Native  34,86
## 3 3 Siberia    SI       60       100 Continental            Native  32,34
## 4 4 Siberia    SI       60       100 Continental            Native  34,78
##   Height Wing.Chord Colour    Sex Nesting.Site Nesting.Height Number.of.Eggs
## 1  12.87       6.67  Brown   Male         &lt;NA&gt;             NA             NA
## 2  13.68       6.79   Grey   Male         &lt;NA&gt;             NA             NA
## 3  12.66       6.64  Black Female        Shrub           35.6              1
## 4  15.09       7.00  Brown Female        Shrub          47.75              0
##   Egg.Weight Flock Home.Range Flock.Size Predator.Presence Predator.Type
## 1         NA     B      Large         16               Yes         Avian
## 2         NA     B      Large         16               Yes         Avian
## 3       3.21     C      Large         14               Yes         Avian
## 4         NA     E      Large         10               Yes         Avian
</code></pre>
<pre><code class="language-r">tail(Data_df, n = 4)
</code></pre>
<pre><code>##         X           Site Index Latitude Longitude Climate Population.Status
## 1065 1065 Falkland Isles    FI   -51.75    -59.17 Coastal        Introduced
## 1066 1066 Falkland Isles    FI   -51.75    -59.17 Coastal        Introduced
## 1067 1067 Falkland Isles    FI   -51.75    -59.17 Coastal        Introduced
## 1068 1068 Falkland Isles    FI   -51.75    -59.17 Coastal        Introduced
##      Weight Height Wing.Chord Colour  Sex Nesting.Site Nesting.Height
## 1065  34.25  15.26       7.04   Grey Male                            
## 1066  31.76  12.78       6.67   Grey Male                            
## 1067  31.48  12.49       6.63  Black Male                            
## 1068  31.94  12.96       6.70   Grey Male                            
##      Number.of.Eggs Egg.Weight Flock Home.Range Flock.Size Predator.Presence
## 1065                               A      Large         19               Yes
## 1066                               A      Large         19               Yes
## 1067                               C      Large         18               Yes
## 1068                               A      Large         19               Yes
##      Predator.Type
## 1065         Avian
## 1066         Avian
## 1067         Avian
## 1068         Avian
</code></pre>
<p>When having an initial look at the results of <code>head(Data_df)</code> and <code>tail(Data_df)</code> we can spot two important things:</p>
<ul>
<li><code>NA</code>s in head and tail of our data set are stored differently. This is a common problem with biological data sets and we will deal with this issue extensively in the next few sections of this document.</li>
<li>Due to our data loading procedure we ended up with a redundant first column that is simply showing the respective row numbers. However, this is unnecessary in <code>R</code> and so we can delete this column as seen below.</li>
</ul>
<pre><code class="language-r">Data_df &lt;- Data_df[,-1] # eliminating the erroneous first column as it is redundant
dim(Data_df) # checking if the elimination went right
</code></pre>
<pre><code>## [1] 1068   20
</code></pre>
<h3 id="the-summary-function">The <code>Summary()</code> Function</h3>
<p>As already stated in our seminar series, the <code>summary()</code> function is <em>invaluable</em> to data exploration and data inspection. However, it is only partially applicable as it will not work flawlessly on every class of data. Examples of this are shown below.</p>
<p>The weight data contained within our data frame should be numeric and thus pose no issue to the <code>summary()</code> function. However, as shown in the next section, it is currently of type character which leads the <code>summary()</code> function to work improperly.</p>
<pre><code class="language-r">summary(Data_df$Weight)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>The height data within our data set, on the other hand, is stored correctly as class numeric. Thus the <code>summary()</code> function performs flawlessly.</p>
<pre><code class="language-r">summary(Data_df$Height)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.35   13.52   14.52   15.39   16.22  135.40
</code></pre>
<p>Making data inspection more easy, one may which to automate the use of the <code>summary()</code> function. However, this only makes sense, when every data column is presenting data in the correct class type. Therefore, we will first fix the column classes and then use the <code>summary()</code> command.</p>
<h2 id="data-cleaning-workflow">Data Cleaning Workflow</h2>
<h3 id="identifying-problems">Identifying Problems</h3>
<p>Indentifying most problems in any data set you may ever encounter comes down to mostly two manifestations of inadequate data entry or handling:</p>
<p>**1. Types/Classes  **<br>
Before even opening a data set, we should know what kind of data classes we expect for every variable (for example, height records as a <code>factor</code> don&rsquo;t make much sense). Problems with data/variable classes can have lasting influence on your analyses and so we need to test the class for each variable (column) individually. Before we alter any column classes, we will first need to identify columns whose classes need fixing. Doing so is as easy applying the <code>class()</code> function to the data contained within every column of our data frame separately.<br>
<code>R</code> offers multiple functions for this but I find the <code>lapply()</code> function to perform flawlessly as shown below. Since <code>lapply()</code> returns a <code>list</code> of class identifiers and these don&rsquo;t translate well to paper, I have opted to transform the list into a named character vector using the <code>unlist()</code> command. One could also use the <code>str()</code> function.</p>
<pre><code class="language-r">unlist(lapply(Data_df, class))
</code></pre>
<pre><code>##              Site             Index          Latitude         Longitude 
##       &quot;character&quot;       &quot;character&quot;         &quot;numeric&quot;         &quot;numeric&quot; 
##           Climate Population.Status            Weight            Height 
##       &quot;character&quot;       &quot;character&quot;       &quot;character&quot;         &quot;numeric&quot; 
##        Wing.Chord            Colour               Sex      Nesting.Site 
##         &quot;numeric&quot;       &quot;character&quot;       &quot;character&quot;       &quot;character&quot; 
##    Nesting.Height    Number.of.Eggs        Egg.Weight             Flock 
##       &quot;character&quot;       &quot;character&quot;       &quot;character&quot;       &quot;character&quot; 
##        Home.Range        Flock.Size Predator.Presence     Predator.Type 
##       &quot;character&quot;         &quot;integer&quot;       &quot;character&quot;       &quot;character&quot;
</code></pre>
<p>For further inspection, one may want to combine the information obtained by using the <code>class()</code> function with either the <code>summary()</code> function (for all non-numeric records) or the <code>hist</code> function (particularly useful for numeric records).</p>
<p>**2. Contents/Values  **<br>
Typos and the like will always lead to some data that simply doesn&rsquo;t make sense given the context of your project. Sometimes, errors like these are salvageable but doing so can be a very difficult process. Before we alter any column contents, we will first need to identify columns whose contents need fixing, however. Doing so is as easy applying an automated version of <code>summary()</code> to the data contained within every column of our data frame separately after having fixed possibly erroneous data classes.</p>
<h3 id="fixing-the-problems">Fixing The Problems</h3>
<p>Fixing the problems in our data sets always comes down to altering data classes, altering faulty values or removing them entirely.<br>
To make sure we fix all problems, we may often wish to enlist the <code>summary()</code> function as well as the <code>hist()</code> function for data inspection and visualisation.</p>
<p>Before we alter any column contents, we will first need to identify columns whose contents need fixing.</p>
<!-- Doing so is as easy applying an automated version of `summary()` to the data contained within every column of our data frame separately which is now possible since we have fixed the column types.   -->
<!-- The code below does exactly that: -->
<!-- ```{r ColContProblems} -->
<!-- for(i in 1:dim(Data_df)[2]){ -->
<!--   print(colnames(Data_df)[i]) -->
<!--   print(summary(Data_df[,i])) -->
<!--   print("------------------------------------------------------") -->
<!-- } -->
<!-- ``` -->
<!-- There are some glaring issues her which we will address in the following sections. -->
<h2 id="our-data">Our Data</h2>
<h3 id="site">Site</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (only 11 possible values)</p>
<h4 id="identifying-problems-1">Identifying Problems</h4>
<p>Let&rsquo;s asses our Site records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Site)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Site)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="index">Index</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (only 11 possible values)</p>
<h4 id="identifying-problems-2">Identifying Problems</h4>
<p>Let&rsquo;s asses our Index records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Index)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Index)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to. Pay attention that thes shortened index numbers lign up with the numbers of site records!</p>
<h4 id="fixing-problems-1">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<p>\newpage</p>
<h3 id="latitude">Latitude</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (Latitude is inherently continuous)</p>
<h4 id="identifying-problems-3">Identifying Problems</h4>
<p>Let&rsquo;s asses our Latitude records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Latitude)
</code></pre>
<pre><code>## [1] &quot;numeric&quot;
</code></pre>
<pre><code class="language-r">table(Data_df$Latitude) # use this instead of summary due to station-dependency here
</code></pre>
<pre><code>## 
## -51.75    -25  -21.1      4   10.5  17.25     31     54     55     60     70 
##     69     88     95    250    114    105     81     68     68     66     64
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-2">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="longitude">Longitude</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (Longitude is inherently continuous)</p>
<h4 id="identifying-problems-4">Identifying Problems</h4>
<p>Let&rsquo;s asses our Longitude records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Longitude)
</code></pre>
<pre><code>## [1] &quot;numeric&quot;
</code></pre>
<pre><code class="language-r">table(Data_df$Longitude) # use this instead of summary due to station-dependency here
</code></pre>
<pre><code>## 
##    -97    -92    -90 -88.75    -67 -59.17    -53     -2   55.6    100    135 
##     68     81     64    105    114     69    250     68     95     66     88
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-3">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="climate">Climate</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (three levels: coastal, semi-coastal, continental)</p>
<h4 id="identifying-problems-5">Identifying Problems</h4>
<p>Let&rsquo;s asses our Climate records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Climate)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Climate)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-4">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="population-status">Population Status</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (two levels: native, introduced)</p>
<h4 id="identifying-problems-6">Identifying Problems</h4>
<p>Let&rsquo;s asses our Population Status records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Population.Status)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Population.Status)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-5">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="weight">Weight</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (weight is a continuous metric)</p>
<h4 id="identifying-problems-7">Identifying Problems</h4>
<p>Let&rsquo;s asses our Weight records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Weight)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Weight)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Obviously, something is wrong.</p>
<h4 id="fixing-problems-6">Fixing Problems</h4>
<p>As seen above, weight records are currently stored as character which they shouldn&rsquo;t. So how do we fix this?</p>
<p>Firstly, let&rsquo;s try an intuitive <code>as.numeric()</code> approach which attempts to convert all values contained within a vector into numeric records.</p>
<pre><code class="language-r">Data_df$Weight &lt;- as.numeric(Data_df_base$Weight)
</code></pre>
<pre><code>## Warning: NAs introduced by coercion
</code></pre>
<pre><code class="language-r">summary(Data_df$Weight)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   19.38   26.34   30.38   29.40   31.87  420.00      66
</code></pre>
<p>Apparently, this didn&rsquo;t do the trick since weight data values (recorded in g) below 13 and above 40 are highly unlikely for <em>Passer domesticus</em>.</p>
<p>Sometimes, the <code>as.numeric()</code> can be made more powerful by handing it data of class <code>character</code>. To do so, simply combine <code>as.numeric()</code> with <code>as.character()</code> as shown below.</p>
<pre><code class="language-r">Data_df$Weight &lt;- as.numeric(as.character(Data_df_base$Weight))
</code></pre>
<pre><code>## Warning: NAs introduced by coercion
</code></pre>
<pre><code class="language-r">summary(Data_df$Weight)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   19.38   26.34   30.38   29.40   31.87  420.00      66
</code></pre>
<p>That still didn&rsquo;t resolve our problem. Weight measurements were taken for all study organisms and so there shouldn&rsquo;t be any <code>NA</code>s and yet we find 66.</p>
<p>Interestingly enough this is the exact same number as observations available for Siberia. A closer look at the data frame shows us that weight data for Siberia has been recorded with commas as decimal delimiters whilst the rest of the data set utilises dots.</p>
<p>Fixing this is not necessarily difficult but it is an erroneous issue for data handling which comes up often and is easy to avoid. Getting rid of the flaws is as simple as using the <code>gsub()</code> function contained within the <code>dplyr</code> package.</p>
<pre><code class="language-r">Data_df$Weight &lt;- as.numeric(gsub(pattern = &quot;,&quot;, replacement = &quot;.&quot;, x = Data_df_base$Weight))
summary(Data_df$Weight)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   19.38   27.90   30.63   29.69   32.24  420.00
</code></pre>
<p>There is one data record left hat exceeds the biologically viable span for body weight records of <em>Passer domesticus</em>. This data record holds the value 420. Since this is unlikely to be a simple mistake of placing the decimal delimiter in the wrong place (both 4.2 and 42 grams are also not feasible weight records for house sparrows), we have to delete the weight data record in question:</p>
<pre><code class="language-r">Data_df$Weight[which(Data_df_base$Weight == 420)] &lt;- NA 
summary(Data_df$Weight)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   19.38   27.89   30.63   29.33   32.23   36.66       1
</code></pre>
<pre><code class="language-r">hist(Data_df$Weight, breaks = 100)
</code></pre>
<p><img src="07---Data-Handling-and-Data-Mining_files/figure-html/ColContWeight-1.png" width="576" /></p>
<p>We finally fixed it!</p>
<h3 id="height">Height</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (height is a continuous metric)</p>
<h4 id="identifying-problems-8">Identifying Problems</h4>
<p>Let&rsquo;s asses our Height records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Height)
</code></pre>
<pre><code>## [1] &quot;numeric&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Height)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.35   13.52   14.52   15.39   16.22  135.40
</code></pre>
<p>Again, some of our data don&rsquo;t behave the way the should (a 135.4 or  1.35 cm tall sparrow are just absurd).</p>
<h4 id="fixing-problems-7">Fixing Problems</h4>
<p>Height (or &ldquo;Length&rdquo;) records of <em>Passer domesticus</em> should fall roughly between 10cm and 22cm. Looking at the data which exceed these thresholds, it is apparent that these are generated simply through misplaced decimal delimiters. So we fix them as follows and use a histogram to check if it worked.</p>
<pre><code class="language-r">Data_df$Height[which(Data_df$Height &lt; 10)] # decimal point placed wrong here
</code></pre>
<pre><code>## [1] 1.350 1.446
</code></pre>
<pre><code class="language-r">Data_df$Height[which(Data_df$Height &lt; 10)] &lt;- Data_df$Height[which(Data_df$Height &lt; 10)] * 10 # FIXED IT!
Data_df$Height[which(Data_df$Height &gt; 22)] # decimal point placed wrong here
</code></pre>
<pre><code>## [1] 126.7 135.4
</code></pre>
<pre><code class="language-r">Data_df$Height[which(Data_df$Height &gt; 22)] &lt;- Data_df$Height[which(Data_df$Height &gt; 22)]/10 # FIXED IT!
summary(Data_df$Height)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   11.09   13.52   14.51   15.20   16.20   21.68
</code></pre>
<pre><code class="language-r">hist(Data_df$Height, breaks = 100)
</code></pre>
<p><img src="07---Data-Handling-and-Data-Mining_files/figure-html/ColContHeight-1.png" width="576" /></p>
<p>We finally fixed it!</p>
<h3 id="wing-chord">Wing Chord</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (wing chord is a continuous metric)</p>
<h4 id="identifying-problems-9">Identifying Problems</h4>
<p>Let&rsquo;s asses our Wing Chord records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Wing.Chord)
</code></pre>
<pre><code>## [1] &quot;numeric&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Wing.Chord)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   6.410   6.840   7.050   7.337   7.400   9.000
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-8">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="colour">Colour</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (three levels: black, grey, brown)</p>
<h4 id="identifying-problems-10">Identifying Problems</h4>
<p>Let&rsquo;s asses our Colour records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Colour)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Colour)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Some of the colour records are very odd.</p>
<h4 id="fixing-problems-9">Fixing Problems</h4>
<p>The colour records &ldquo;Bright black&rdquo; and &ldquo;Grey with black spots&rdquo; should be &ldquo;Grey&rdquo;. Someone clearly got too eager on the assignment of colours here. The fix is as easy as identifying the data records which are &ldquo;too precise&rdquo; and overwrite them with the correct assignment:</p>
<pre><code class="language-r">Data_df$Colour[which(Data_df$Colour == &quot;Bright black&quot;)] &lt;- &quot;Grey&quot;
Data_df$Colour[which(Data_df$Colour == &quot;Grey with black spots&quot;)] &lt;- &quot;Grey&quot;
Data_df$Colour &lt;- droplevels(factor(Data_df$Colour)) # drop unused factor levels
summary(Data_df$Colour) # FIXED IT!
</code></pre>
<pre><code>## Black Brown  Grey 
##   356   298   414
</code></pre>
<p>We finally fixed it!</p>
<h3 id="sex">Sex</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (two levels: male and female)</p>
<h4 id="identifying-problems-11">Identifying Problems</h4>
<p>Let&rsquo;s asses our Climate records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Sex)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Sex)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-10">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="nesting-site">Nesting Site</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (two levels: shrub and tree)</p>
<h4 id="identifying-problems-12">Identifying Problems</h4>
<p>Let&rsquo;s asses our Nesting Site records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Nesting.Site)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Nesting.Site)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1068 character character
</code></pre>
<h4 id="fixing-problems-11">Fixing Problems</h4>
<p>One individual is recording to be nesting on the ground. This is something house sparrows don&rsquo;t do. Therefore, we have to assume that this individual is not even a <em>Passer domesticus</em> to begin with.</p>
<p>The only way to solve this is to remove all observations pertaining to this individual:</p>
<pre><code class="language-r">Data_df &lt;- Data_df[-which(Data_df$Nesting.Site == &quot;Ground&quot;), ]
summary(Data_df$Nesting.Site)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>We just deleted a data record. This affects the flock size of the flock it belongs to (basically, this column contains hard-coded values) which we are going to deal with later.<br>
Still, there are manually entered <code>NA</code> records present which we have to get rid of. These can be fixed easily without altering column classes and simply making use of logic by indexing their dependencies on other column values. The nesting site for a data record where sex reads &ldquo;Male&rdquo; has to be <code>NA</code>.</p>
<pre><code class="language-r">Data_df$Nesting.Site[which(Data_df$Sex == &quot;Male&quot;)] &lt;- NA 
Data_df$Nesting.Site &lt;- droplevels(factor(Data_df$Nesting.Site)) # drop unused factor levels
summary(Data_df$Nesting.Site)# FIXED IT!
</code></pre>
<pre><code>## Shrub  Tree  NA's 
##   292   231   544
</code></pre>
<h3 id="nesting-height">Nesting Height</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (continuous records in two clusters corresponding to shrubs and trees)</p>
<h4 id="identifying-problems-13">Identifying Problems</h4>
<p>Let&rsquo;s asses our Nesting Height records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Nesting.Height)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Nesting.Height)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>There are obviously some issues here.</p>
<h4 id="fixing-problems-12">Fixing Problems</h4>
<p>Nesting height is a clear example of a variable that should be recorded as <code>numeric</code> and yet our data frame currently stores them as character.</p>
<p>Our first approach to fixing this, again, is using the <code>as.numeric()</code> function.</p>
<pre><code class="language-r">summary(as.numeric(Data_df$Nesting.Height))
</code></pre>
<pre><code>## Warning in summary(as.numeric(Data_df$Nesting.Height)): NAs introduced by
## coercion
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   11.78   42.34   64.85  480.59  951.38 1950.86     544
</code></pre>
<p>Clearly, something went horribly wrong here. When taking a closer look, the number of 1s is artificially inflated. This is due to the <code>NA</code>s contained within the data set. These are currently stored as characters since they have been entered into the Excel sheet itself. The <code>as.numeric()</code> function transforms these into 1s.</p>
<p>One way of circumventing this issue is to combine the <code>as.numeric()</code> function with the <code>as.character()</code> function.</p>
<pre><code class="language-r">Data_df$Nesting.Height &lt;- as.numeric(as.character(Data_df$Nesting.Height))
</code></pre>
<pre><code>## Warning: NAs introduced by coercion
</code></pre>
<pre><code class="language-r">summary(Data_df$Nesting.Height)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   11.78   42.34   64.85  480.59  951.38 1950.86     544
</code></pre>
<p>This quite clearly fixed our problems.</p>
<!-- As can be seen in the histograms below there are now far less erroneously small values. -->
<!-- ```{r plottingpanesNestingHeight, fig.height=2.75} -->
<!-- par(mfrow=c(1,2)) # plotting panes as 1 by 2 -->
<!-- hist(as.numeric(Data_df_base$Nesting.Height), main = "Numeric(Data)", breaks = 100) -->
<!-- hist(as.numeric(as.character(Data_df_base$Nesting.Height)), main = "Numeric(Character(Data))", breaks = 100) -->
<!-- ``` -->
<h3 id="number-of-eggs">Number of Eggs</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (no a priori knowledge of levels)</p>
<h4 id="identifying-problems-14">Identifying Problems</h4>
<p>Let&rsquo;s asses our Number of Eggs records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Number.of.Eggs)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Number.of.Eggs)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>One very out of the ordinary record is to be seen.</p>
<h4 id="fixing-problems-13">Fixing Problems</h4>
<p>Number of eggs is another variable which should be recorded as <code>numeric</code> and yet is currently stored as character.</p>
<p>Our first approach to fixing this, again, is using the <code>as.numeric()</code> function.</p>
<pre><code class="language-r">summary(as.numeric(Data_df$Number.of.Eggs))
</code></pre>
<pre><code>## Warning in summary(as.numeric(Data_df$Number.of.Eggs)): NAs introduced by
## coercion
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   0.000   2.000   3.000   3.746   4.000  10.000     544
</code></pre>
<p>Again, this didn&rsquo;t do the trick. The number of 1s might be inflated and we expect exactly 544 (number of males) <code>NA</code>s since number of eggs have only been recorded for female house sparrows.</p>
<p>We already know that improperly stored <code>NA</code> records are prone to causing an inflation of data records of value 1. We also remember that head and tail of our data frame hold different types of <code>NA</code> records. Let&rsquo;s find out who entered <code>NA</code>s correctly:</p>
<pre><code class="language-r">unique(Data_df$Site[which(is.na(Data_df$Egg.Weight))])
</code></pre>
<pre><code>## character(0)
</code></pre>
<p>The code above identifies the sites at which proper <code>NA</code> recording has been done. The Falkland Isle team did it right (<code>NA</code> fields in Excel were left blank). Fixing this is actually a bit more challenging and so we do the following:</p>
<pre><code class="language-r"># make everything into characters
Data_df$Number.of.Eggs &lt;- as.character(Data_df$Number.of.Eggs) 
# writing character NA onto actual NAs
Data_df$Number.of.Eggs[which(is.na(Data_df$Number.of.Eggs))] &lt;- &quot;  NA&quot;
# make all character NAs into proper NAs
Data_df$Number.of.Eggs[Data_df$Number.of.Eggs == &quot;  NA&quot;] &lt;- NA 
# make everything numeric
Data_df$Number.of.Eggs &lt;- as.numeric(as.character(Data_df$Number.of.Eggs))
</code></pre>
<pre><code>## Warning: NAs introduced by coercion
</code></pre>
<pre><code class="language-r">summary(Data_df$Number.of.Eggs)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   0.000   2.000   3.000   3.746   4.000  10.000     544
</code></pre>
<p>We did it!</p>
<h3 id="egg-weight">Egg Weight</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (another weight measurement that needs to be continuous)</p>
<h4 id="identifying-problems-15">Identifying Problems</h4>
<p>Let&rsquo;s asses our Egg Weight records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Egg.Weight)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Egg.Weight)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<h4 id="fixing-problems-14">Fixing Problems</h4>
<p>Egg weight should be recorded as <code>numeric</code> and yet is currently stored as character. Our first approach to fixing this, again, is using the <code>as.numeric()</code> function again.</p>
<pre><code class="language-r">summary(as.numeric(Data_df$Egg.Weight))
</code></pre>
<pre><code>## Warning in summary(as.numeric(Data_df$Egg.Weight)): NAs introduced by coercion
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   1.580   2.340   2.670   2.619   2.890   3.590     590
</code></pre>
<p>Something is wrong here. Not enough <code>NA</code>s are recorded. We expect exactly 590 <code>NA</code>s (Number of males + Number of Females with zero eggs). Additionally, there are way too many 1s.
Our problem, again, lies with the way the <code>NA</code>s have been entered into the data set from the beginning and so we use the following fix again.</p>
<pre><code class="language-r"># make everything into characters
Data_df$Egg.Weight &lt;- as.character(Data_df$Egg.Weight) 
# writing character NA onto actual NAs
Data_df$Egg.Weight[which(is.na(Data_df$Egg.Weight))] &lt;- &quot;  NA&quot; 
# make all character NAs into proper NAs
Data_df$Egg.Weight[Data_df$Egg.Weight == &quot;  NA&quot;] &lt;- NA 
# make everything numeric
Data_df$Egg.Weight &lt;- as.numeric(as.character(Data_df$Egg.Weight))
summary(Data_df$Egg.Weight)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   1.580   2.340   2.670   2.619   2.890   3.590     590
</code></pre>
<h3 id="flock">Flock</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (each sparrow was assigned to one particular flock)</p>
<h4 id="identifying-problems-16">Identifying Problems</h4>
<p>Let&rsquo;s asses our Flock records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Flock)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Flock)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-15">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="home-range">Home Range</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (three levels: small, medium, large)</p>
<h4 id="identifying-problems-17">Identifying Problems</h4>
<p>Let&rsquo;s asses our Home Range records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Home.Range)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Home.Range)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-16">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="flock-size">Flock Size</h3>
<p><strong>Variable Class Expectation:</strong> <code>numeric</code> (continuous measurement of how many sparrows are in each flock - measured as integers)</p>
<h4 id="identifying-problems-18">Identifying Problems</h4>
<p>Let&rsquo;s asses our Flock Size records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Flock.Size)
</code></pre>
<pre><code>## [1] &quot;integer&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Flock.Size)
</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    7.00   16.00   19.00   25.81   31.00   58.00
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-17">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="predator-presence">Predator Presence</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (two levels: yes and no)</p>
<h4 id="identifying-problems-19">Identifying Problems</h4>
<p>Let&rsquo;s asses our Predator Presence records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Predator.Presence)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Predator.Presence)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>Indeed, they do behave just like we&rsquo;d expect them to.</p>
<h4 id="fixing-problems-18">Fixing Problems</h4>
<p>We don&rsquo;t need to fix anything here.</p>
<h3 id="predator-type">Predator Type</h3>
<p><strong>Variable Class Expectation:</strong> <code>factor</code> (three levels: Avian, Non-Avian, and <code>NA</code>)</p>
<h4 id="identifying-problems-20">Identifying Problems</h4>
<p>Let&rsquo;s asses our Predator Type records for our <em>Passer domesticus</em> individuals and check whether they behave as expected:</p>
<pre><code class="language-r">class(Data_df$Predator.Type)
</code></pre>
<pre><code>## [1] &quot;character&quot;
</code></pre>
<pre><code class="language-r">summary(Data_df$Predator.Type)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>Something doesn&rsquo;t sit well here.</p>
<h4 id="fixing-problems-19">Fixing Problems</h4>
<p>Someone got overly eager when recording Predator Type and specified the presence of a hawk instead of taking down &ldquo;Avian&rdquo;. We fix this as follows:</p>
<pre><code class="language-r">Data_df$Predator.Type[which(Data_df$Predator.Type == &quot;Hawk&quot;)] &lt;- &quot;Avian&quot;
summary(Data_df$Predator.Type)
</code></pre>
<pre><code>##    Length     Class      Mode 
##      1067 character character
</code></pre>
<p>This fixed it  but there are still manually entered <code>NA</code> records present which we have to get rid of. These can be fixed easily without altering column classes and simply making use of logic by indexing their dependencies on other column values. The predator type for a data record where predator presence reads &ldquo;No&rdquo; has to be <code>NA</code>.</p>
<pre><code class="language-r">Data_df$Predator.Type[which(Data_df$Predator.Presence == &quot;No&quot;)] &lt;- NA 
Data_df$Predator.Type &lt;- droplevels(factor(Data_df$Predator.Type)) # drop unused factor levels
summary(Data_df$Predator.Type)# FIXED IT!
</code></pre>
<pre><code>##     Avian Non-Avian      NA's 
##       490       220       357
</code></pre>
<h3 id="redundant-data">Redundant Data</h3>
<p>Our data contains redundant columns (i.e.: columns whose data is present in another column already). These are (1) Flock Size (data contained in Flock column) and (2) Flock.Size (data contained in Index column). The fix to this is as easy as removing the columns in question.</p>
<pre><code class="language-r">Data_df &lt;- within(Data_df, rm(Flock.Size, Site))
dim(Data_df)
</code></pre>
<pre><code>## [1] 1067   18
</code></pre>
<p>Fixed it!</p>
<p>By doing so, we have gotten rid of our flock size problem stemming from the deletion of a data record. You could also argue that the columns <code>Site</code> and <code>Index</code> are redundant. We keep both for quality-of-life when interpreting our results (make use of <code>Sites</code>) and coding (make use os <code>Index</code>).</p>
<h2 id="saving-the-fixed-data-set">Saving The Fixed Data Set</h2>
<p>We fixed out entire data set! The data set is now ready for use.</p>
<p>Keep in mind that the data set I provided you with was relatively clean and real-world messy data sets can be far more difficult to clean up.</p>
<p>Before going forth, we need to save it. <strong>Attention:</strong> don&rsquo;t overwrite your initial data file!</p>
<h3 id="final-check">Final Check</h3>
<p>Before exporting you may want to ensure that everything is in order and do a final round of data inspection. This can be achieved by running the automated <code>summary()</code> command from earlier again as follows. I am not including the output here to save some space.</p>
<pre><code class="language-r">for(i in 1:dim(Data_df)[2]){
  print(colnames(Data_df)[i])
  print(summary(Data_df[,i]))
  print(&quot;------------------------------------------------------&quot;)
}
</code></pre>
<p>Everything checks out. Let&rsquo;s save our final data frame.</p>
<h3 id="exporting-the-altered-data">Exporting The Altered Data</h3>
<p>Since Excel is readily available for viewing data outside of R, I like to save my final data set in excel format as can be seen below. Additionally, I recommend saving your final data frame as an RDS file. These are <code>R</code> specific data files which you will not be able to alter outside of <code>R</code> thus saving yourself from accidentally changing records when only trying to view your data. On top of that, RDS files take up less space than either Excel or TXT files do.</p>
<pre><code class="language-r"># saving in excel sheet
write.csv(Data_df, file = paste(Dir.Data, &quot;/SparrowData_FIXED.csv&quot;, sep=&quot;&quot;))
# saving as R data frame object
saveRDS(Data_df, file = paste(Dir.Data, &quot;/1 - Sparrow_Data_READY.rds&quot;, sep=&quot;&quot;)) 
</code></pre>

          </div>

          

<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/r/">R</a>
  
  <a class="badge badge-light" href="/tag/statistics/">Statistics</a>
  
</div>



          
          <div class="article-widget">
            
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/courses/an-introduction-to-biostatistics/06-inferential-statistics-hypotheses-and-our-research-project/" rel="next">Inferential Statistics, Hypotheses And Our Research Project</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/courses/an-introduction-to-biostatistics/nominal-tests/" rel="prev">Nominal Tests</a>
  </div>
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          <p>Last updated on 2020-06-10</p>

          





          


          


  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/courses/biostat101/data-handling-and-data-mining/">Data Handling and Data Mining</a></li>
      
      <li><a href="/courses/biostat101/a-primer-for-statistical-tests/">A Primer For Statistical Tests</a></li>
      
      <li><a href="/courses/an-introduction-to-biostatistics/a-primer-for-statistical-tests/">A Primer For Statistical Tests</a></li>
      
      <li><a href="/courses/an-introduction-to-biostatistics/correlation-tests/">Correlation Tests</a></li>
      
      <li><a href="/courses/biostat101/correlation-tests/">Correlation Tests</a></li>
      
    </ul>
  </div>
  



        </div>

      </article>

      <footer class="site-footer">
  

  <p class="powered-by">
    © 2024
  </p>

  
  






  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
  </p>
</footer>


    </main>
  </div>
</div>


      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/latex.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.66c553246b0f279a03be6e5597f72b52.js"></script>

    






  
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
