<!DOCTYPE html><html lang="en-gb" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Erik Kusch">

  
  
  
    
  
  <meta name="description" content="Kriging specifications and considerations with `KrigR`.">

  
  <link rel="alternate" hreflang="en-gb" href="https://www.erikkusch.com/courses/krigr/kriging/">

  


  
  
  
  <meta name="theme-color" content="#858383">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cutive+Mono%7CLora:400,700%7CRoboto:400,700&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-186216138-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-186216138-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu7658c99d512131214e4d6c003a3f85f7_112593_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://www.erikkusch.com/courses/krigr/kriging/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@ErikKusch">
  <meta property="twitter:creator" content="@ErikKusch">
  
  <meta property="og:site_name" content="Erik Kusch">
  <meta property="og:url" content="https://www.erikkusch.com/courses/krigr/kriging/">
  <meta property="og:title" content="Statistical Downscaling | Erik Kusch">
  <meta property="og:description" content="Kriging specifications and considerations with `KrigR`."><meta property="og:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg">
  <meta property="twitter:image" content="https://www.erikkusch.com/img/%C3%A5motdalshytta.jpg"><meta property="og:locale" content="en-gb">
  
    
      <meta property="article:published_time" content="2022-05-26T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2021-05-26T20:00:00&#43;01:00">
  

  



  


  


  





  <title>Statistical Downscaling | Erik Kusch</title>

</head>
<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  








  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/images/logo_huab2266ff59bbac6a094b6da1268adcf9_208479_0x70_resize_lanczos_2.png" alt="Erik Kusch"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-center" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/"><span>Home</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Courses & Workshops</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/courses/krigr/"><span>KrigR - State-of-the-Art Climate Data within R</span></a>
            
              <a class="dropdown-item" href="/courses/gbif/"><span>Accessing and Referencing GBIF Data for Research</span></a>
            
              <a class="dropdown-item" href="/courses/rethinking/"><span>Statistical Rethinking - Introduction to Bayesian Statistics</span></a>
            
              <a class="dropdown-item" href="/courses/bayes-nets/"><span>Bayesian Networks - Causality through Bayesian Approaches</span></a>
            
              <a class="dropdown-item" href="/courses/biostat101/"><span>Biostats 101 - An Introduction to Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/excursions-into-biostatistics/"><span>Biostats 301 - Excursions into Biostatistics</span></a>
            
              <a class="dropdown-item" href="/courses/bftp-biome-detection/"><span>BFTP - First Steps in Macroecology in R</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/about"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://htmlpreview.github.io/?https://github.com/ErikKusch/Homepage/blob/master/static/media/CV_ErikKusch.html" target="_blank" rel="noopener"><span>CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  

<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
  <input name="q" type="search" class="form-control" placeholder="Search..." autocomplete="off">
  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/krigr/">Introduction</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/courses/krigr/">Motivation &amp; Workshop</a>
      </li>
      
      <li >
        <a href="/courses/krigr/background/">The Theory Behind KrigR</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/krigr/setup/">Quick Start</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/courses/krigr/setup/">Setting up KrigR</a>
      </li>
      
      <li >
        <a href="/courses/krigr/quickstart/">Quick Guide</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/courses/krigr/prep/">Workshop</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/courses/krigr/prep/">Preparing the Workshop</a>
      </li>
      
      <li >
        <a href="/courses/krigr/download/">Downloading &amp; Processing</a>
      </li>
      
      <li class="active">
        <a href="/courses/krigr/kriging/">Statistical Downscaling</a>
      </li>
      
      <li >
        <a href="/courses/krigr/bioclim/">Bioclimatic Variables</a>
      </li>
      
      <li >
        <a href="/courses/krigr/third-party/">Third-Party Data</a>
      </li>
      
      <li >
        <a href="/courses/krigr/projections/">Projection Downscaling</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

    </div>

    
    <div class="d-none d-xl-block col-xl-2 docs-toc">
      <ul class="nav toc-top">
        <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
      </ul>

      <nav id="TableOfContents">
  <ul>
    <li><a href="#covariates">Covariates</a>
      <ul>
        <li><a href="#considerations-for-download_dem">Considerations for <code>download_DEM()</code></a></li>
      </ul>
    </li>
    <li><a href="#kriging">Kriging</a>
      <ul>
        <li><a href="#spatial-limitation">Spatial Limitation</a></li>
        <li><a href="#localisation-of-results">Localisation of Results</a></li>
        <li><a href="#considerations-for-krigr">Considerations for <code>krigR()</code></a></li>
      </ul>
    </li>
    <li><a href="#aggregate-uncertainty">Aggregate Uncertainty</a></li>
    <li><a href="#session-info">Session Info</a></li>
  </ul>
</nav>

      
    </div>
    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

      <article class="article">

        <div class="docs-article-container">
          <h1>Statistical Downscaling</h1>

          <div class="article-style">
            <p><div class="alert alert-danger">
  <div>
    <strong><code>KrigR</code> is currently undergoing development. As a result, this part of the workshop has become deprecated. Please refer to the <a href="/courses/krigr/setup/">setup</a> <a href="/courses/krigr/quickstart/">quick guide</a> portions of this material as these are up-to-date. </strong>
  </div>
</div>
</p>
<div class="alert alert-danger">
  <div>
    This part of the workshop is dependant on set-up and preparation done previously <a href="/courses/krigr/prep/">here</a>.
  </div>
</div>
<p>First, we load <code>KrigR</code>:</p>
<pre><code class="language-r">library(KrigR)
</code></pre>
<div class="alert alert-info">
  <div>
    Statistical downscaling with <code>KrigR</code> is handled via the <code>krigR()</code> function and requires a set of spatial covariates.
  </div>
</div>
<div class="alert alert-warning">
  <div>
    For an introduction to the statistical downscaling process, I will first walk you through the <code>SpatialPolygons</code> spatial preference.
  </div>
</div>
<p>First, we load the data we wish to statistically downscale. We established these data 
<a href="/courses/krigr/download//#climate-data">here</a>.</p>
<pre><code class="language-r">SpatialPolygonsRaw &lt;- stack(file.path(Dir.Data, &quot;SpatialPolygonsRaw.nc&quot;))
</code></pre>
<p>We are now ready to begin our journey to high-spatial resolution data products!</p>
<h2 id="covariates">Covariates</h2>
<p>First, we use the <code>download_DEM()</code> function which comes with <code>KrigR</code> to obtain elevation data as our covariate of choice. This produces two rasters:</p>
<ol>
<li>A raster of <strong>training</strong> resolution which matches the input data in all attributes except for the data in each cell.</li>
<li>A raster of <strong>target</strong> resolution which matches the input data as closely as possible in all attributes except for the resolution (which is specified by the user).</li>
</ol>
<p>Both of these products are bundled into a <code>list</code> where the first element corresponds to the <em>training</em> resolution and the second element contains the <em>target</em> resolution covariate data. Here, we specify a target resolution of <code>.02</code>.</p>
<p>This is how we specify <code>download_DEM()</code> to prepare DEM covariates for us:</p>
<pre><code class="language-r">Covs_ls &lt;- download_DEM(Train_ras = SpatialPolygonsRaw, # the data we want to downscale
                        Target_res = .02, # the resolution we want to downscale to
                        Shape = Shape_shp, # extra spatial preferences
                        Dir = Dir.Covariates # where to store the covariate files
                        )
</code></pre>
<p>For now, let&rsquo;s simply inspect our list of covariate rasters:</p>
<pre><code class="language-r">Covs_ls
</code></pre>
<pre><code>## [[1]]
## class      : RasterLayer 
## dimensions : 34, 54, 1836  (nrow, ncol, ncell)
## resolution : 0.1000189, 0.09999998  (x, y)
## extent     : 9.726991, 15.12801, 49.75, 53.15  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : DEM 
## values     : 20.11554, 861.7248  (min, max)
## 
## 
## [[2]]
## class      : RasterLayer 
## dimensions : 204, 324, 66096  (nrow, ncol, ncell)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 9.72486, 15.12486, 49.74986, 53.14986  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : DEM 
## values     : 15.75, 1128  (min, max)
</code></pre>
<p>You will find that the target resolution covariate data comes at a resolution of 0.017 instead of the 0.02 resolution we specified. This happens because <code>download_DEM()</code> calls upon the <code>raster::aggregate()</code> function when aggregating the high-resolution covariate data to your desired target resolution and is thus only capable of creating target-resolution covariates in multiples of the base resolution of the GMTED 2010 DEM we are using as our default covariate. This happens only when the <code>Target_res</code> argument is specified to be a number.</p>
<div class="alert alert-warning">
  <div>
    Specifying the <code>Target_res</code> argument as a number will lead to best approximation of the desired resolution due to usage of the <code>raster::aggregate()</code> within <code>download_DEM()</code>. If you need an exact resolution to match pre-existing data, please refer to <a href="/courses/krigr/third-party/#matching-third-party-data">this part of the workshop</a>.
  </div>
</div>
<p>Notice that despite the covariate rasters (and input rasters, for that matter) containing 1836 and 6.6096\times 10^{4} for training and target resolution respectively, we only obtain data for 826 and 26247 cells respectively due to our specification of <code>SpatialPolygons</code>. This will come in handy when doing the statistical interpolation (see 
<a href="/courses/krigr/kriging/#spatial-limitation">this section</a> for details).</p>
<p>Before moving on, let&rsquo;s visualise the covariate data:</p>
<pre><code class="language-r">Plot_Covs(Covs_ls, Shape_shp)
</code></pre>
<p><img src="krigr-downscaling_files/figure-html/unnamed-chunk-3-1.png" width="1440" /></p>
<p>Notice just how much more clearly the mountainous areas in our study region show up at our target resolution.</p>
<h3 id="considerations-for-download_dem">Considerations for <code>download_DEM()</code></h3>
<h4 id="target_res"><code>Target_res</code></h4>
<p>Alternatively to specifying a target resolution, you can specify a different raster which should be matched in all attributes by the raster at target resolution. We get to this again when discussing 
<a href="/courses/krigr/third-party/#matching-third-party-data">third-party</a> data usage.</p>
<div class="alert alert-">
  <div>
    <code>Target_res</code> can be used for a numeric input or to match a pre-existing <code>raster</code> object.
  </div>
</div>
<h4 id="shape"><code>Shape</code></h4>
<p>Spatial preferences with <code>download_DEM()</code> are specified slightly differently when compared to <code>download_ERA()</code>. Whereas <code>download_ERA()</code> uses the <code>Extent</code> argument, <code>download_DEM()</code> uses the <code>Shape</code> argument. The reason? <code>download_DEM()</code> automatically reads out the extent of the input raster and carries out <code>extent</code> limitation according to this. <code>SpatialPolygons</code> and <code>data.frame</code> inputs are supported. For clarity, we simply recognise them with the <code>Shape</code> argument to avoid confusion and unnecessary <code>extent</code> inputs.</p>
<div class="alert alert-">
  <div>
    Spatial preferences are handed to <code>download_DEM()</code> using the <code>Shape</code> argument.
  </div>
</div>
<h4 id="keep_temporary"><code>Keep_Temporary</code></h4>
<p>By default, this argument is set to <code>FALSE</code> and raw, global DEM data will be deleted when the covariates you queried have been established. Setting this argument to <code>TRUE</code> will retain the raw data and make it so you do not have to re-download the DEM data for later use.</p>
<div class="alert alert-">
  <div>
    Setting <code>Keep_Temporary = TRUE</code> will retain global DEM data on your hard drive.
  </div>
</div>
<h4 id="source"><code>Source</code></h4>
<p>This argument specifies where to download the DEM data from. By default, we query the data from the official USGS website. However, this website has given some users issues with connection instabilities. Consequently, the raw DEM data is also available from a dropbox which you can query download from by setting <code>Source = &quot;Drive&quot;</code>.</p>
<div class="alert alert-">
  <div>
    When experiencing connection issues with the USGS servers, we recommend setting <code>Source = &quot;Drive&quot;</code> to obtain covariate data.
  </div>
</div>
<h2 id="kriging">Kriging</h2>
<div class="alert alert-danger">
  <div>
    Kriging can be a very <strong>computationally expensive</strong> exercise.
  </div>
</div>
<p>The expense of kriging is largely determined by three factors:</p>
<ol>
<li>Change in spatial resolution.</li>
<li>Number of cells containing data; i.e. 
<a href="/courses/krigr/kriging/#spatial-limitation">Spatial Limitation</a>.</li>
<li>Localisation of Kriging; i.e. 
<a href="/courses/krigr/kriging/#spatial-limitation">Localisation of Results</a>.</li>
</ol>
<div class="alert alert-warning">
  <div>
    We explore two of these further down in this workshop material. For more information, please consult <a href="https://iopscience.iop.org/article/10.1088/1748-9326/ac39bf">this publication (Figure 4)</a>.
  </div>
</div>
<p>Finally, we are ready to interpolate our input data given our covariates with the <code>krigR()</code> function:</p>
<pre><code class="language-r">SpatialPolygonsKrig &lt;- krigR(Data = SpatialPolygonsRaw, # data we want to krig as a raster object
      Covariates_coarse = Covs_ls[[1]], # training covariate as a raster object
      Covariates_fine = Covs_ls[[2]], # target covariate as a raster object
      Keep_Temporary = FALSE, # we don't want to retain the individually kriged layers on our hard-drive
      Cores = 1, # we want to krig on just one core
      FileName = &quot;SpatialPolygonsKrig&quot;, # the file name for our full kriging output
      Dir = Dir.Exports # which directory to save our final input in
      )
</code></pre>
<pre><code>## Commencing Kriging
</code></pre>
<pre><code>## Kriging of remaining 3 data layers should finish around: 2023-04-03 16:35:08
</code></pre>
<pre><code>## 
  |                                                                                      
  |                                                                                |   0%
  |                                                                                      
  |====================                                                            |  25%
  |                                                                                      
  |========================================                                        |  50%
  |                                                                                      
  |============================================================                    |  75%
  |                                                                                      
  |================================================================================| 100%
</code></pre>
<p>Just like with the <code>download_ERA()</code> function, <code>krigR()</code> updates you on what it is currently working on. Again, I implemented this to make sure people don&rsquo;t get too anxious staring at an empty console in <code>R</code>. If this feature is not appealing to you, you can turn this progress tracking off by setting <code>verbose = FALSE</code> in the function call to <code>krigR()</code>.</p>
<div class="alert alert-warning">
  <div>
    For the rest of this workshop, I suppress messages from <code>krigR()</code> via other means so that when you execute, you get progress tracking.
  </div>
</div>
<p>There we go. As output of the <code>krigR()</code> function, we obtain a list of downscaled data as the first element and downscaling standard errors as the second list element. Let&rsquo;s look at that:</p>
<pre><code class="language-r">SpatialPolygonsKrig[-3] # we will talk later about the third element
</code></pre>
<pre><code>## $Kriging_Output
## class      : RasterBrick 
## dimensions : 175, 309, 54075, 4  (nrow, ncol, ncell, nlayers)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 9.87486, 15.02486, 50.14986, 53.06653  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : var1.pred.1, var1.pred.2, var1.pred.3, var1.pred.4 
## min values :    269.3269,    266.6584,    265.8426,    261.2555 
## max values :    275.0150,    273.3421,    272.1410,    270.0713 
## 
## 
## $Kriging_SE
## class      : RasterBrick 
## dimensions : 175, 309, 54075, 4  (nrow, ncol, ncell, nlayers)
## resolution : 0.01666667, 0.01666667  (x, y)
## extent     : 9.87486, 15.02486, 50.14986, 53.06653  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : var1.stdev.1, var1.stdev.2, var1.stdev.3, var1.stdev.4 
## min values :    0.1184605,    0.1265206,    0.1142046,    0.1283697 
## max values :    0.1308865,    0.1426154,    0.1535409,    0.2638671
</code></pre>
<p>All the data has been downscaled and we do have uncertainties recorded for all of our outputs. Let&rsquo;s visualise the data:</p>
<pre><code class="language-r">Plot_Krigs(SpatialPolygonsKrig, 
           Shp = Shape_shp,
           Dates = c(&quot;01-1995&quot;, &quot;02-1995&quot;, &quot;03-1995&quot;, &quot;04-1995&quot;)
           )
</code></pre>
<p><img src="krigr-downscaling_files/figure-html/KrigPlot-1.png" width="1440" /></p>
<p>As you can see, the elevation patterns show up clearly in our kriged air temperature output. Furthermore, you can see that our certainty of Kriging predictions drops on the 04/01/1995 in comparison to the preceding days. However, do keep in mind that a maximum standard error of 0.131, 0.143, 0.154, 0.264 (for each layer of our output respectively) on a total range of data of 5.688, 6.684, 6.298, 8.816 (again, for each layer in the output respectively) is evident of a downscaling result we can be confident in. We also demonstrated reliability of kriging in 
<a href="https://iopscience.iop.org/article/10.1088/1748-9326/ac39bf" target="_blank" rel="noopener">this publication (Figure 3)</a>.</p>
<p>Finally, this <code>SpatialPolygons</code>-informed downscaling took roughly 57 minutes on my machine (this may vary drastically on other devices).</p>
<h3 id="spatial-limitation">Spatial Limitation</h3>
<div class="alert alert-info">
  <div>
    Kriging can be sped up tremendously by limiting downscaling efforts to smaller regions.
  </div>
</div>
<p>To demonstrate how spatial limitation affects computational time, we downscale all of our remaining 
<a href="/courses/krigr/download//#climate-data">target data</a> (i.e., <code>extent</code> and <code>data.frame</code> time-series specifications).</p>
<details><summary> Click here for kriging calls </summary>
<h4 id="extent-data"><code>extent</code> Data</h4>
<h4 id="point-data-dataframe">Point-Data (<code>data.frame</code>)</h4>
<pre><code class="language-r">PtsRaw &lt;- stack(file.path(Dir.Data, &quot;PointsRaw.nc&quot;))
Covs_ls &lt;- download_DEM(Train_ras = PtsRaw,
                        Target_res = .02,
                        Shape = Mountains_df,
                        Buffer = 0.5,
                        ID = &quot;Mountain&quot;,
                        Dir = Dir.Covariates,
                        Keep_Temporary = TRUE)
PtsKrig &lt;- krigR(Data = PtsRaw, 
      Covariates_coarse = Covs_ls[[1]], 
      Covariates_fine = Covs_ls[[2]], 
      Keep_Temporary = FALSE, 
      Cores = 1, 
      FileName = &quot;PointsKrig&quot;,
      Dir = Dir.Exports
      )
</code></pre>
</details>
<p>How long did the kriging for each data set take? Let me list these out to highlight just how much of a difference the spatial limitation makes here:</p>
<ol>
<li><code>extent</code> specification (7344 data cells in training resolution) - roughly 30 minutes</li>
<li><code>SpatialPolygons</code> specification (3752 data cells in training resolution) - roughly 4 minutes</li>
<li>Point (<code>data.frame</code>) specification (1908 data cells in training resolution) - roughly 30 seconds</li>
</ol>
<p>As you can see, there is a huge benefit to reducing the cells containing data to speed up computation. But what is the impact of doing so for our 
<a href="/courses/krigr/prep/#points-of-interest-dataframe">points of interest</a>?</p>
<details><summary> Click here for data extraction and plotting </summary>
<pre><code class="language-r">Extract_df &lt;- data.frame(
  AirTemp = c(
    raster::extract(
      x = SpatialPolygonsKrig[[1]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]), 
    raster::extract(
      x = ExtKrig[[1]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]), 
    raster::extract(
      x = PtsKrig[[1]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)])
  ), 
  Uncertainty = c(
    raster::extract(
      x = SpatialPolygonsKrig[[2]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]), 
    raster::extract(
      x = ExtKrig[[2]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)]), 
    raster::extract(
      x = PtsKrig[[2]][[1]],
      y = Mountains_df[, c(&quot;Lon&quot;, &quot;Lat&quot;)])
  ), 
  Mountain = rep(Mountains_df$Mountain, 3),
  Spatial = rep(c(&quot;Polygons&quot;, &quot;Extent&quot;, &quot;Points&quot;), 
                each = nrow(Mountains_df))
)
</code></pre>
<pre><code class="language-r">ggplot(data = Extract_df, aes(y = Mountain, x = AirTemp, col = Spatial)) +
  geom_point(cex = 5, pch = 18) +
  geom_errorbar(aes(xmin = AirTemp - Uncertainty/2, 
                    xmax = AirTemp + Uncertainty/2)) +
  theme_bw()
</code></pre>
</details>
<p><img src="krigr-downscaling_files/figure-html/unnamed-chunk-12-1.png" width="1440" /></p>
<p>As you can see, the differences between the different data sets at our points of interest are noticeable and often times not negligible (as far as statistical interpolation uncertainty, i.e., error bars) are concerned.</p>
<div class="alert alert-danger">
  <div>
    <p>When statistically downscaling data products it is <strong>vital you inspect the output data</strong> for inconsistencies or other issues.</p>
<p><strong>Kriging is not a one-size-fits all solution to spatial resolution needs!</strong></p>
  </div>
</div>
<h3 id="localisation-of-results">Localisation of Results</h3>
<div class="alert alert-warning">
  <div>
    By default Kriging of the <code>krigR()</code> function uses all cells in a spatial product to downscale individual cells of rasters.
  </div>
</div>
<div class="alert alert-info">
  <div>
    The <code>nmax</code> argument can circumvent this.
  </div>
</div>
<p>Let’s build further on our above example by adding the <code>nmax</code> argument (passed on to <code>gstat::krige()</code>) to our <code>krigR()</code> function call. This argument controls how many of the closest cells the Kriging algorithm should consider in the downscaling of individual coarse, training cells.</p>
<p>First, we need to re-establish our covariate data:</p>
<pre><code class="language-r">Covs_ls &lt;- download_DEM(Train_ras = SpatialPolygonsRaw,
                        Target_res = .02,
                        Shape = Shape_shp,
                        Dir = Dir.Covariates,
                        Keep_Temporary = TRUE)
</code></pre>
<p>Now we may use locally weighted kriging:</p>
<pre><code class="language-r">SpatialPolygonsLocalKrig &lt;- krigR(Data = SpatialPolygonsRaw,
      Covariates_coarse = Covs_ls[[1]],
      Covariates_fine = Covs_ls[[2]],
      Keep_Temporary = FALSE,
      Cores = 1, 
      nmax = 10,
      FileName = &quot;SpatialPolygonsLocalKrig&quot;,
      Dir = Dir.Exports
      )
Plot_Krigs(SpatialPolygonsLocalKrig, 
           Shp = Shape_shp,
           Dates = c(&quot;01-1995&quot;, &quot;02-1995&quot;, &quot;03-1995&quot;, &quot;04-1995&quot;)
           )
</code></pre>
<p><img src="krigr-downscaling_files/figure-html/KrigShpLocal-1.png" width="1440" /></p>
<p>The air temperature prediction/downscaling results look just like the ones that we obtained above (we will investigate this claim in a second here). However, we seriously improved our localised understanding of Kriging uncertainties (i.e., we see much more localised patterns of Kriging standard error). In the case of our study region, uncertainties seem to be highest for areas where the landscape is dominated by large, abrupt changes in elevation (e.g. around the mountainous areas) and water-dominated areas such as streams and lakes (e.g. the lakes around Leipzig in the North of Saxony).</p>
<div class="alert alert-info">
  <div>
    Using the <code>nmax</code> argument helps to identify highly localised patterns in the Kriging uncertainty as well as predictions!
  </div>
</div>
<p>Now let&rsquo;s investigate how much of a difference there is between our two predictions of statistically downscaled air temperature when using locally weighted kriging or domain-average kriging as before:</p>
<pre><code class="language-r">Plot_Raw(SpatialPolygonsLocalKrig[[1]]-SpatialPolygonsKrig[[1]], 
         Shp = Shape_shp,
         Dates = c(&quot;01-1995&quot;, &quot;02-1995&quot;, &quot;03-1995&quot;, &quot;04-1995&quot;))
</code></pre>
<p><img src="krigr-downscaling_files/figure-html/KrigShpLocalDiff-1.png" width="1440" /></p>
<p>Again, limiting the number of data points that the Kriging algorithm has access to changes the data we obtain. Therefore, let me reiterate:</p>
<div class="alert alert-danger">
  <div>
    <p>When statistically downscaling data products it is <strong>vital you inspect the output data</strong> for inconsistencies or other issues.</p>
<p><strong>Kriging is not a one-size-fits all solution to spatial resolution needs!</strong></p>
  </div>
</div>
<h3 id="considerations-for-krigr">Considerations for <code>krigR()</code></h3>
<p><code>krigR()</code> is a complex function with many things happening under the hood. To make sure you have the best experience with this function, I have compiled a few bits of <em>good-to-know</em> information about the workings of <code>krigR()</code>.</p>
<h4 id="cores"><code>Cores</code></h4>
<p>Kriging is computationally expensive and can be a time-consuming exercise first and foremost. However, the <code>gstat::krige()</code> function which <code>krigR()</code> makes calls to, and which carries out the kriging itself, does not support multi-core processing. Conclusively, we can hand separate kriging jobs to separate cores in our machines and drastically reduce computation time. We do so via the <code>Cores</code> argument.</p>
<div class="alert alert-">
  <div>
    Using the <code>Cores</code> argument, <code>krigR()</code> carries out parallel kriging of multi-layer rasters.
  </div>
</div>
<h4 id="nmax-and-maxdist"><code>nmax</code> and <code>maxdist</code></h4>
<p>Localised kriging is achieved through either <code>nmax</code> or <code>maxdist</code>.</p>
<div class="alert alert-warning">
  <div>
    When using <code>nmax</code> or <code>maxdist</code>, we recommend you ensure that the distance represented by these arguments approximates the area of typical weather system (around 150km).
  </div>
</div>
<p>For the purpose of showing clear patterns in the localisation of uncertainty patterns, we did not to so in the above.</p>
<h4 id="keep_temporary-1"><code>Keep_Temporary</code></h4>
<p>Kriging is time-consuming. Particularly for multi-layer rasters with many layers. To make it so you can interrupt kriging of multi-layer rasters and resume the process at a later time, we have implemented temporary file saving. <code>krigR()</code> checks for presence of temporary files and only loads already kriged layers rather than kriging them again. Upon completion and saving of the final output, you may choose to delete the temporary files or keep them.</p>
<h4 id="krigingequation"><code>KrigingEquation</code></h4>
<p><code>krigR()</code> can accommodate any covariate pair (training and target resolution) you supply. However, when using 
<a href="/courses/krigr/third-party/#third-party-data-covariates">third-party covariates</a> in non-linear combinations, you will need to use the <code>KrigingEquation</code> argument to do so.</p>
<div class="alert alert-">
  <div>
    With the <code>KrigingEquation</code> argument, you may specify non-linear combinations of covariates for your call to <code>krigR()</code>.
  </div>
</div>
<h4 id="kriging-reliability">Kriging Reliability</h4>
<p>Kriging reliability and robustness is largely dependant on the statistical link between your target variable and covariates of your choice.</p>
<div class="alert alert-danger">
  <div>
    <strong>Elevation will not be a useful covariate for all climate variables!</strong>
  </div>
</div>
<p>We demonstrate that Kriging is a reliable interpolation method when carefully choosing covariates in 
<a href="https://iopscience.iop.org/article/10.1088/1748-9326/ac39bf" target="_blank" rel="noopener">this publication (Figure 3)</a>. One large factor in reliability of kriging is the change in resolution between training and target resolutions - as a rule of thumb, we do not recommend downscaling representing more than roughly one order of magnitude. If you attempt to do so <code>krigR()</code> will throw a warning message, but proceed regardless.</p>
<div class="alert alert-warning">
  <div>
    Kriging is a very flexible tool for statistical interpolation. Consider your choice of covariates and change in resolutions carefully. <strong>Always inspect your data</strong>.
  </div>
</div>
<h4 id="call-list">Call List</h4>
<p>So far, we have only ever looked at the first two elements in the list returned by <code>krigR()</code>. A quick look at the help file, the code, or this guide reveals that there is a third list element - the <em>call list</em>. When coding this feature into <code>krigR()</code> I intended for this to be a neat, clean, storage-friendly way of keeping track of how the spatial product was created. It does so without storing additional spatial products. Let&rsquo;s have a look at it:</p>
<details><summary> Click here for call list query and output </summary>
<pre><code class="language-r">SpatialPolygonsKrig[[3]]
</code></pre>
<pre><code>## $Data
## $Data$Class
## [1] &quot;RasterStack&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Data$Dimensions
## $Data$Dimensions$nrow
## [1] 34
## 
## $Data$Dimensions$ncol
## [1] 54
## 
## $Data$Dimensions$ncell
## [1] 1836
## 
## 
## $Data$Extent
## class      : Extent 
## xmin       : 9.726991 
## xmax       : 15.12801 
## ymin       : 49.75 
## ymax       : 53.15 
## 
## $Data$CRS
## Coordinate Reference System:
## Deprecated Proj.4 representation: +proj=longlat +datum=WGS84 +no_defs 
## WKT2 2019 representation:
## GEOGCRS[&quot;unknown&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         ID[&quot;EPSG&quot;,6326]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##         ID[&quot;EPSG&quot;,8901]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]]] 
## 
## $Data$layers
## [1] &quot;X1&quot; &quot;X2&quot; &quot;X3&quot; &quot;X4&quot;
## 
## 
## $Covariates_coarse
## $Covariates_coarse$Class
## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Covariates_coarse$Dimensions
## $Covariates_coarse$Dimensions$nrow
## [1] 34
## 
## $Covariates_coarse$Dimensions$ncol
## [1] 54
## 
## $Covariates_coarse$Dimensions$ncell
## [1] 1836
## 
## 
## $Covariates_coarse$Extent
## class      : Extent 
## xmin       : 9.726991 
## xmax       : 15.12801 
## ymin       : 49.75 
## ymax       : 53.15 
## 
## $Covariates_coarse$CRS
## Coordinate Reference System:
## Deprecated Proj.4 representation: +proj=longlat +datum=WGS84 +no_defs 
## WKT2 2019 representation:
## GEOGCRS[&quot;unknown&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         ID[&quot;EPSG&quot;,6326]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##         ID[&quot;EPSG&quot;,8901]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]]] 
## 
## $Covariates_coarse$layers
## [1] &quot;DEM&quot;
## 
## 
## $Covariates_fine
## $Covariates_fine$Class
## [1] &quot;RasterLayer&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;
## 
## $Covariates_fine$Dimensions
## $Covariates_fine$Dimensions$nrow
## [1] 204
## 
## $Covariates_fine$Dimensions$ncol
## [1] 324
## 
## $Covariates_fine$Dimensions$ncell
## [1] 66096
## 
## 
## $Covariates_fine$Extent
## class      : Extent 
## xmin       : 9.72486 
## xmax       : 15.12486 
## ymin       : 49.74986 
## ymax       : 53.14986 
## 
## $Covariates_fine$CRS
## Coordinate Reference System:
## Deprecated Proj.4 representation: +proj=longlat +datum=WGS84 +no_defs 
## WKT2 2019 representation:
## GEOGCRS[&quot;unknown&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         ID[&quot;EPSG&quot;,6326]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##         ID[&quot;EPSG&quot;,8901]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433,
##                 ID[&quot;EPSG&quot;,9122]]]] 
## 
## $Covariates_fine$layers
## [1] &quot;DEM&quot;
## 
## 
## $KrigingEquation
## ERA ~ DEM
## &lt;environment: 0x7fee0d4450e8&gt;
## 
## $Cores
## [1] 1
## 
## $FileName
## [1] &quot;SpatialPolygonsKrig&quot;
## 
## $Keep_Temporary
## [1] FALSE
## 
## $nmax
## [1] Inf
## 
## $Data_Retrieval
## [1] &quot;None needed. Data was not queried via krigR function, but supplied by user.&quot;
</code></pre>
</details>
<p>This lengthy list should contain all information you need to trace how you created a certain data set using <code>krigR()</code>. If you feel like anything is missing in this list, please contact us.</p>
<h2 id="aggregate-uncertainty">Aggregate Uncertainty</h2>
<div class="alert alert-danger">
  <div>
    Every climate data product is subject to an error-rate / range of data uncertainty. Unfortunately, <strong>almost none</strong> of the established climate data products <strong>communicate associated uncertainties</strong>. This leads to a dangerous <strong>overestimation of data credibility</strong>.
  </div>
</div>
<div class="alert alert-info">
  <div>
    With the <code>KrigR</code> workflow, it is trivial to obtain uncertainty flags for all of your data - no matter the spatial or temporal resolution.
  </div>
</div>
<p>To understand the full certainty of our data obtained via the <code>KrigR</code> workflow, we should combine 
<a href="/courses/krigr/download/#dynamical-data-uncertainty">dynamical uncertainty</a> with the statistical uncertainty we obtained from the <code>krigR()</code> function call above.</p>
<p>To do so, we require two data sets:</p>
<ul>
<li><code>SpatialPoylgonsKrig</code> - 
<a href="/courses/krigr/kriging/#kriging">created above</a> containing statistical uncertainty in the second list position</li>
<li><code>SpatialPoylgonsEns</code> - 
<a href="/courses/krigr/download/#dynamical-data-uncertainty-1">created here</a>; 
<a href="/courses/krigr/Data/SpatialPolygonsEns.nc">download here</a> containing dynamical uncertainty</li>
</ul>
<p>First, we load the data and assign them to objects with shorter names:</p>
<pre><code class="language-r">SpatialPolygonsEns &lt;- stack(file.path(Dir.Data, &quot;SpatialPolygonsEns.nc&quot;))
DynUnc &lt;- SpatialPolygonsEns
KrigUnc &lt;- SpatialPolygonsKrig[[2]]
</code></pre>
<p>Next, we need to align the rasters of statistical uncertainty (resolution: 0.017) and dynamical uncertainty (resolution: 0.5). As you can see, these are of differing resolutions and so cannot easily be combined using raster math. Instead, we first disaggregate the coarser-resolution raster (<code>DynUnc</code>) as disaggregation does not attempt any interpolation thus preserving the data, but representing it with smaller cells. To fix final remaining alignment issues, we allow for some resampling between the two raster:</p>
<pre><code class="language-r">EnsDisagg &lt;- disaggregate(DynUnc, fact=res(DynUnc)[1]/res(KrigUnc)[1])
DynUnc &lt;- resample(EnsDisagg, KrigUnc)
</code></pre>
<p>Finally, we combine the two uncertainty data products to form an aggregate uncertainty product:</p>
<pre><code class="language-r">FullUnc &lt;- DynUnc + KrigUnc
</code></pre>
<p>Now, we are ready to plot our aggregate uncertainty:</p>
<pre><code class="language-r">Plot_Raw(FullUnc, 
         Shp = Shape_shp, 
         Dates = c(&quot;01-1995&quot;, &quot;02-1995&quot;, &quot;03-1995&quot;, &quot;04-1995&quot;), 
         COL = rev(viridis(100)))
</code></pre>
<p><img src="krigr-downscaling_files/figure-html/unnamed-chunk-17-1.png" width="1440" /></p>
<p>As you can see, at short time-scales dynamic uncertainty eclipses statistical uncertainty. However, this phenomenon reverses at longer time-scales as shown in 
<a href="https://iopscience.iop.org/article/10.1088/1748-9326/ac39bf" target="_blank" rel="noopener">this publication (Figure 1)</a>.</p>
<h2 id="session-info">Session Info</h2>
<pre><code class="language-r">sessionInfo()
</code></pre>
<pre><code>## R version 4.2.3 (2023-03-15)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Big Sur ... 10.16
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] mapview_2.11.0          rnaturalearthdata_0.1.0 rnaturalearth_0.3.2    
##  [4] gimms_1.2.1             ggmap_3.0.2             cowplot_1.1.1          
##  [7] viridis_0.6.2           viridisLite_0.4.1       ggplot2_3.4.1          
## [10] tidyr_1.3.0             KrigR_0.1.2             terra_1.7-21           
## [13] httr_1.4.5              stars_0.6-0             abind_1.4-5            
## [16] fasterize_1.0.4         sf_1.0-12               lubridate_1.9.2        
## [19] automap_1.1-9           doSNOW_1.0.20           snow_0.4-4             
## [22] doParallel_1.0.17       iterators_1.0.14        foreach_1.5.2          
## [25] rgdal_1.6-5             raster_3.6-20           sp_1.6-0               
## [28] stringr_1.5.0           keyring_1.3.1           ecmwfr_1.5.0           
## [31] ncdf4_1.21             
## 
## loaded via a namespace (and not attached):
##  [1] leafem_0.2.0             colorspace_2.1-0         class_7.3-21            
##  [4] leaflet_2.1.2            satellite_1.0.4          base64enc_0.1-3         
##  [7] rstudioapi_0.14          proxy_0.4-27             farver_2.1.1            
## [10] fansi_1.0.4              codetools_0.2-19         cachem_1.0.7            
## [13] knitr_1.42               jsonlite_1.8.4           png_0.1-8               
## [16] Kendall_2.2.1            compiler_4.2.3           assertthat_0.2.1        
## [19] fastmap_1.1.1            cli_3.6.0                htmltools_0.5.4         
## [22] tools_4.2.3              gtable_0.3.1             glue_1.6.2              
## [25] dplyr_1.1.0              Rcpp_1.0.10              jquerylib_0.1.4         
## [28] vctrs_0.6.1              blogdown_1.16            crosstalk_1.2.0         
## [31] lwgeom_0.2-11            xfun_0.37                timechange_0.2.0        
## [34] lifecycle_1.0.3          rnaturalearthhires_0.2.1 zoo_1.8-11              
## [37] scales_1.2.1             gstat_2.1-0              yaml_2.3.7              
## [40] curl_5.0.0               memoise_2.0.1            gridExtra_2.3           
## [43] sass_0.4.5               reshape_0.8.9            stringi_1.7.12          
## [46] highr_0.10               e1071_1.7-13             boot_1.3-28.1           
## [49] intervals_0.15.3         RgoogleMaps_1.4.5.3      rlang_1.1.0             
## [52] pkgconfig_2.0.3          bitops_1.0-7             evaluate_0.20           
## [55] lattice_0.20-45          purrr_1.0.1              htmlwidgets_1.6.1       
## [58] labeling_0.4.2           tidyselect_1.2.0         plyr_1.8.8              
## [61] magrittr_2.0.3           bookdown_0.33            R6_2.5.1                
## [64] generics_0.1.3           DBI_1.1.3                pillar_1.8.1            
## [67] withr_2.5.0              units_0.8-1              xts_0.13.0              
## [70] tibble_3.2.1             spacetime_1.2-8          KernSmooth_2.23-20      
## [73] utf8_1.2.3               rmarkdown_2.20           jpeg_0.1-10             
## [76] grid_4.2.3               zyp_0.11-1               FNN_1.1.3.2             
## [79] digest_0.6.31            classInt_0.4-9           webshot_0.5.4           
## [82] stats4_4.2.3             munsell_0.5.0            bslib_0.4.2
</code></pre>

          </div>

          

<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/climate-data/">Climate Data</a>
  
  <a class="badge badge-light" href="/tag/statistical-downscaling/">Statistical Downscaling</a>
  
  <a class="badge badge-light" href="/tag/krigr/">KrigR</a>
  
</div>



          
          <div class="article-widget">
            
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/courses/krigr/download/" rel="next">Downloading &amp; Processing</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/courses/krigr/bioclim/" rel="prev">Bioclimatic Variables</a>
  </div>
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          <p>Last updated on 2021-05-26</p>

          





          


          


  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/courses/krigr/bioclim/">Bioclimatic Variables</a></li>
      
      <li><a href="/courses/krigr/download/">Downloading &amp; Processing</a></li>
      
      <li><a href="/courses/krigr/prep/">Preparing the Workshop</a></li>
      
      <li><a href="/courses/krigr/projections/">Projection Downscaling</a></li>
      
      <li><a href="/courses/krigr/quickstart/">Quick Guide</a></li>
      
    </ul>
  </div>
  



        </div>

      </article>

      <footer class="site-footer">
  

  <p class="powered-by">
    © 2024
  </p>

  
  






  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
  </p>
</footer>


    </main>
  </div>
</div>


      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/latex.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.66c553246b0f279a03be6e5597f72b52.js"></script>

    






  
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
